import {store} from './store.js';import {loadWeather,weatherIcon} from './weather.js';import {loadNews,buildExecutiveSummary} from './news.js';
const $=x=>document.querySelector(x), all=x=>[...document.querySelectorAll(x)], toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)};
let calCursor=new Date();let slideTimer;const promptLibrary={
'Self-Love':['What part of you deserves tenderness today?','Where are you already enough?','What boundary would feel like self-respect?'],Growth:['What are you ready to outgrow?','Which small brave choice is next?','What lesson are you finally ready to use?'],Gratitude:['What ordinary thing quietly helped today?','Who made life lighter recently?','What would you miss if it disappeared tomorrow?'],Motherhood:['Where did joy show up with Lani today?','What does good-enough motherhood look like today?','What memory from this season deserves saving?'],Career:['What payments concept became clearer today?','Which skill would make work feel easier?','What professional win are you undercounting?'],Mindset:['Which thought needs a better replacement?','Where are you making progress invisible?','What would ten percent more trust change?'],Reflection:['What did today ask of you?','What can remain unfinished without guilt?','What should tomorrow inherit from today?'],Dreams:['Describe the life you are unlocking.','What would you pursue with ten percent more courage?','Which dream needs a date, not just hope?']};let activePrompt='Self-Love';
function freshPrompt(cat){const state=store.get(),history=state.journalPromptHistory[cat]||[];let candidates=promptLibrary[cat].filter(p=>!history.includes(p));if(!candidates.length)candidates=promptLibrary[cat];const p=candidates[Math.floor(Math.random()*candidates.length)];store.mutate(d=>{d.journalPromptHistory[cat]=[...(d.journalPromptHistory[cat]||[]),p].slice(-promptLibrary[cat].length)});return p}
export async function dashboard(router){all('[data-jump]').forEach(b=>b.onclick=()=>router.go(b.dataset.jump));const wg=$('#weatherGrid');wg.innerHTML='<div class="muted">Loading weather…</div>';const results=await loadWeather();wg.innerHTML=results.map(c=>`<article class="weather-card"><div class="mini">${c.name}</div><div class="metric">${c.time}</div><div>${weatherIcon(c.code)} ${c.temp==null?'Weather unavailable':`${Math.round(c.temp)}° · H ${Math.round(c.high)}° / L ${Math.round(c.low)}°`}</div></article>`).join('');$('#weatherStatus').textContent=results.some(x=>x.temp!=null)?'Live via Open-Meteo':'Clocks live · weather offline';renderDashAgenda();renderDashLani();all('[data-top3]').forEach(c=>c.onchange=()=>store.mutate(d=>d.top3Done[+c.dataset.top3]=c.checked));$('#editTop3').onclick=()=>{const vals=prompt('Enter three priorities separated by |',store.get().top3.join(' | '));if(vals!==null)store.set({top3:vals.split('|').map(x=>x.trim()).slice(0,3),top3Done:[false,false,false]})}}
function agendaItems(){const st=store.get();return [...Object.entries(st.calendar).map(([date,v])=>({date,label:v.subject||v.events||'Calendar item',type:'Calendar'})),...st.bills.map(b=>({date:b.due,label:`${b.name} · $${b.amount}`,type:'Bill'}))].filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date))}
function renderDashAgenda(){const today=new Date().toISOString().slice(0,10),end=new Date(Date.now()+7*864e5).toISOString().slice(0,10),items=agendaItems().filter(x=>x.date>=today&&x.date<=end);$('#dashboardAgenda').innerHTML=items.length?items.map(x=>`<div class="agenda-item"><b>${x.label}</b><div class="mini">${x.date} · ${x.type}</div></div>`).join(''):'<p class="muted">Nothing scheduled in the next seven days.</p>'}
function renderDashLani(){const s=store.get(),photo=s.laniPhotos.at(-1);$('#dashboardLani').innerHTML=`${photo?`<img src="${photo}" style="width:100%;height:150px;object-fit:cover;border-radius:16px">`:'<div class="prompt">Add photos in Lani’s Corner.</div>'}<p>${s.laniMemories[0]?.text||'Her newest memory will appear here.'}</p>`}

export function intelligence(){
  const renderReviews=()=>{const el=$('#weeklyReviewList');if(!el)return;const items=store.get().weeklyReviews||[];el.innerHTML=items.length?items.slice(0,6).map(r=>`<div class="entry"><div class="mini">${new Date(r.date).toLocaleDateString()}</div><p>${escapeHTML(r.text)}</p></div>`).join(''):'<p class="muted">Your saved weekly reviews will appear here.</p>'};
  $('#saveWeeklyReview').onclick=()=>{const text=$('#weeklyReviewText').value.trim();if(!text)return toast('Write a quick review first.');store.mutate(d=>d.weeklyReviews.unshift({id:Date.now(),date:new Date().toISOString(),text}));$('#weeklyReviewText').value='';renderReviews();toast('Weekly review saved.')};
  const input=$('#globalSearch'),results=$('#globalSearchResults');input.oninput=()=>{const q=input.value.trim().toLowerCase();if(q.length<2){results.innerHTML='<div class="status">Type at least two characters.</div>';return}const st=store.get(),found=[];Object.entries(st.calendar).forEach(([date,v])=>{const text=[v.subject,v.events,v.tasks,v.notes].join(' ');if(text.toLowerCase().includes(q))found.push({type:'Calendar',title:v.subject||date,detail:date+' · '+text})});st.journalEntries.forEach(v=>{const text=[v.category,v.prompt,v.text].join(' ');if(text.toLowerCase().includes(q))found.push({type:'Journal',title:v.category,detail:v.text})});st.goals.forEach(v=>{if((v.name+' '+v.category).toLowerCase().includes(q))found.push({type:'Goal',title:v.name,detail:`${v.progress||0}% complete`})});st.bills.forEach(v=>{if((v.name+' '+v.category).toLowerCase().includes(q))found.push({type:'Bill',title:v.name,detail:`${usd(v.amount)} · ${v.due||'No date'}`})});st.laniMemories.forEach(v=>{if((v.title+' '+v.text).toLowerCase().includes(q))found.push({type:'Lani Memory',title:v.title,detail:v.text})});st.careerNotes.forEach(v=>{if(v.text.toLowerCase().includes(q))found.push({type:'Career Note',title:'Payments Academy',detail:v.text})});results.innerHTML=found.length?found.slice(0,25).map(v=>`<div class="search-result"><span class="pill">${v.type}</span><div><b>${escapeHTML(v.title)}</b><p>${escapeHTML(v.detail).slice(0,180)}</p></div></div>`).join(''):'<div class="status">No saved information matched that search.</div>'};renderReviews();
}

export function calendar(){renderCalendar();$('#prevMonth').onclick=()=>{calCursor.setMonth(calCursor.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calCursor.setMonth(calCursor.getMonth()+1);renderCalendar()};$('#saveCalendarDay').onclick=()=>{const date=$('#calDate').value;if(!date)return toast('Choose a date.');store.mutate(d=>d.calendar[date]={subject:$('#calSubject').value,events:$('#calEvents').value,tasks:$('#calTasks').value,notes:$('#calNotes').value});renderCalendar();toast('Day saved.')}}
function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth(),state=store.get();$('#monthLabel').textContent=calCursor.toLocaleDateString('en-US',{month:'long',year:'numeric'});const g=$('#calendarGrid');g.innerHTML=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="dow">${x}</div>`).join('')+'<div></div>'.repeat(new Date(y,m,1).getDay());for(let d=1;d<=new Date(y,m+1,0).getDate();d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,v=state.calendar[key];g.insertAdjacentHTML('beforeend',`<button class="day ${key===new Date().toISOString().slice(0,10)?'today':''}" data-day="${key}"><b>${d}</b><div class="mini">${v?.subject||''}</div></button>`)}all('[data-day]').forEach(b=>b.onclick=()=>{const v=state.calendar[b.dataset.day]||{};$('#calDate').value=b.dataset.day;$('#calSubject').value=v.subject||'';$('#calEvents').value=v.events||'';$('#calTasks').value=v.tasks||'';$('#calNotes').value=v.notes||''});const prefix=`${y}-${String(m+1).padStart(2,'0')}`,month=agendaItems().filter(x=>x.date.startsWith(prefix)),today=new Date().toISOString().slice(0,10),end=new Date(Date.now()+7*864e5).toISOString().slice(0,10),next=agendaItems().filter(x=>x.date>=today&&x.date<=end);$('#monthlyAgenda').innerHTML=list(month);$('#next7').innerHTML=list(next)}
const list=xs=>xs.length?xs.map(x=>`<div class="agenda-item"><b>${x.label}</b><div class="mini">${x.date} · ${x.type}</div></div>`).join(''):'<p class="muted">Nothing yet.</p>';
export function lani(){renderLani();const upload=$('#laniUpload');if(upload)upload.onchange=async e=>{const files=[...e.target.files].slice(0,18);for(const file of files){try{const image=await compressLaniPhoto(file);store.mutate(d=>{d.laniPhotos.push(image);d.laniPhotos=d.laniPhotos.slice(-18)})}catch(err){console.warn('Photo skipped',err)}}renderLani();e.target.value=''};all('[data-lani-fact]').forEach(x=>x.oninput=()=>{store.mutate(d=>d.laniFacts[x.dataset.laniFact]=x.value);renderLaniSummary()});$('#saveMemory').onclick=()=>{const text=$('#memoryText').value.trim();if(!text)return;store.mutate(d=>d.laniMemories.unshift({id:crypto.randomUUID?.()||String(Date.now()),date:new Date().toISOString().slice(0,10),title:$('#memoryTitle').value.trim()||'Sweet memory',text}));$('#memoryTitle').value='';$('#memoryText').value='';renderLani()};$('#printLani').onclick=()=>{document.body.classList.add('print-lani');window.print();setTimeout(()=>document.body.classList.remove('print-lani'),500)};$('#laniPrev').onclick=()=>stepLani(-1);$('#laniNext').onclick=()=>stepLani(1);bindLaniChecks()}
function compressLaniPhoto(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Not an image'));const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.src=reader.result};reader.readAsDataURL(file)})}
function stepLani(delta){const st=store.get(),len=st.laniPhotos.length;if(!len)return;store.mutate(d=>d.laniPhotoIndex=((Number(d.laniPhotoIndex)||0)+delta+len)%len);renderLani(false)}
function renderLani(autoplay=true){clearInterval(slideTimer);const st=store.get(),photos=st.laniPhotos||[],box=$('#laniSlideshow');if(!box)return;let idx=Math.min(Number(st.laniPhotoIndex)||0,Math.max(0,photos.length-1));if(idx!==st.laniPhotoIndex)store.mutate(d=>d.laniPhotoIndex=idx);box.innerHTML=photos.length?photos.map((p,i)=>`<img class="${i===idx?'active':''}" src="${p}" alt="Lani memory ${i+1}">`).join(''):'<div class="lani-empty"><span>📸</span><b>Add photos to begin the dynamic collage.</b><small>Favorite moments will softly rotate here.</small></div>';$('#photoCount').textContent=`${photos.length} photo${photos.length===1?'':'s'}`;$('#laniDots').innerHTML=photos.map((_,i)=>`<button class="slide-dot ${i===idx?'active':''}" data-slide="${i}" aria-label="Show photo ${i+1}"></button>`).join('');$('#laniThumbs').innerHTML=photos.map((p,i)=>`<button class="lani-thumb ${i===idx?'active':''}" data-slide="${i}"><img src="${p}" alt=""></button>`).join('');all('[data-slide]').forEach(b=>b.onclick=()=>{store.mutate(d=>d.laniPhotoIndex=Number(b.dataset.slide));renderLani(false)});if(photos.length>1&&autoplay)slideTimer=setInterval(()=>stepLani(1),4500);renderLaniSummary();$('#memoryList').innerHTML=st.laniMemories.length?st.laniMemories.map(m=>`<article class="memory-entry"><span class="memory-dot"></span><div><div class="mini">${m.date}</div><b>${m.title}</b><p>${m.text}</p><button class="text-button" data-delete-memory="${m.id||m.date+m.title}">Remove</button></div></article>`).join(''):'<div class="status">Her saved memories will build a beautiful timeline here.</div>';all('[data-delete-memory]').forEach((b,i)=>b.onclick=()=>{store.mutate(d=>d.laniMemories.splice(i,1));renderLani()});renderLaniChecks()}
function renderLaniSummary(){const st=store.get(),f=st.laniFacts||{},latest=st.laniMemories[0];const line=$('#laniHeroLine');if(line)line.textContent=latest?`${latest.title}: ${latest.text}`:'Add her favorites and newest memory to bring this page to life.';if($('#laniAgePill'))$('#laniAgePill').textContent=`Age ${f.age||'—'}`;if($('#laniHeightPill'))$('#laniHeightPill').textContent=`Height ${f.height||'—'}`;if($('#laniColorPill'))$('#laniColorPill').textContent=`Favorite color ${f.favoriteColor||'—'}`;const snapshot=$('#giftSnapshot');if(snapshot)snapshot.innerHTML=[['Birthday',f.birthday],['Age',f.age],['Height',f.height],['Favorite color',f.favoriteColor],['Top foods',f.foods],['Favorite toys',f.toys],['Favorite shows',f.shows],['Favorite activities',f.activities],['Clothing size',f.clothingSize],['Shoe size',f.shoeSize],['Gift ideas',f.giftIdeas]].map(([k,v])=>`<div class="snapshot-line"><b>${k}</b><span>${v||'—'}</span></div>`).join('')}
const swimLabels={goggles:'Goggles',towel:'Towel',suit:'Swimsuit',snack:'Snack',water:'Water bottle',sunscreen:'Sunscreen'};const prepLabels={outfit:'Choose outfits',bag:'Pack activity bag',calendar:'Check calendar',meal:'Plan favorite meal'};
function renderLaniChecks(){const st=store.get();if($('#swimChecklist'))$('#swimChecklist').innerHTML=Object.entries(swimLabels).map(([k,v])=>`<label class="cute-check"><input type="checkbox" data-lani-check="swim.${k}" ${st.laniSwim?.[k]?'checked':''}><span>${v}</span></label>`).join('');if($('#laniPrepChecklist'))$('#laniPrepChecklist').innerHTML=Object.entries(prepLabels).map(([k,v])=>`<label class="cute-check"><input type="checkbox" data-lani-check="prep.${k}" ${st.laniPrep?.[k]?'checked':''}><span>${v}</span></label>`).join('');bindLaniChecks()}
function bindLaniChecks(){all('[data-lani-check]').forEach(x=>x.onchange=()=>{const [group,key]=x.dataset.laniCheck.split('.');store.mutate(d=>{if(group==='swim')d.laniSwim[key]=x.checked;else d.laniPrep[key]=x.checked})})}
export function career(){const lessons={'Authorization & Capture':'Authorization reserves approval; capture submits the transaction for clearing and settlement.','Settlement & Reconciliation':'Settlement moves value. Reconciliation proves every external and internal record agrees.','Pay-Ins':'Money entering the platform: acceptance, retries, fraud, capture, and settlement.','Pay-Outs':'Money leaving the platform: validation, funding, release, returns, exceptions, and reconciliation.','Chargebacks':'Reason codes, evidence, deadlines, audit trails, and pattern recognition.','ACH & RTP':'Different rails create different speed, finality, return, risk, and operating models.','Fraud & Risk':'Balance approval and loss prevention using identity, velocity, rules, models, and review.'};all('.lesson').forEach(b=>b.onclick=()=>{$('#lessonTitle').textContent=b.dataset.lesson;$('#lessonBody').textContent=lessons[b.dataset.lesson]});$('#saveCareerNote').onclick=()=>{const text=$('#careerNote').value.trim();if(text)store.mutate(d=>d.careerNotes.unshift({date:new Date().toLocaleDateString(),text}));renderCareerNotes()};renderCareerNotes()}
function renderCareerNotes(){$('#careerNoteList').innerHTML=store.get().careerNotes.map(n=>`<div class="entry"><div class="mini">${n.date}</div>${n.text}</div>`).join('')}
export function money(){
  renderMoney();
  $('#saveAccounts').onclick=()=>{store.set({checking:num('#checking'),savings:num('#savings'),otherAssets:num('#otherAssets'),debts:num('#debts'),monthlyIncome:num('#monthlyIncome')});renderMoney();toast('Financial snapshot saved.')};
  $('#addBill').onclick=()=>saveBill();
  $('#cancelBillEdit').onclick=()=>clearBillForm();
  $('#addSavingGoal').onclick=()=>{const name=$('#saveGoalName').value.trim(),target=num('#saveGoalTarget');if(!name||target<=0)return toast('Add a goal name and target.');store.mutate(d=>d.savingsGoals.push({id:Date.now(),name,target,current:num('#saveGoalCurrent'),date:$('#saveGoalDate').value}));clearFields(['#saveGoalName','#saveGoalTarget','#saveGoalCurrent','#saveGoalDate']);renderMoney();toast('Savings goal created.')};
  $('#addSinkingFund').onclick=()=>{const name=$('#fundName').value.trim(),target=num('#fundTarget');if(!name||target<=0)return toast('Add a fund name and target.');store.mutate(d=>d.sinkingFunds.push({id:Date.now(),name,target,current:num('#fundCurrent')}));clearFields(['#fundName','#fundTarget','#fundCurrent']);renderMoney();toast('Sinking fund added.')};
}
const num=sel=>Number($(sel)?.value)||0;
const clearFields=arr=>arr.forEach(x=>{if($(x))$(x).value=''});
function saveBill(){const name=$('#billName').value.trim(),amount=num('#billAmount'),due=$('#billDue').value,id=$('#billEditId').value;if(!name||!due||amount<0)return toast('Add a bill name, amount, and due date.');const bill={id:id?Number(id):Date.now(),name,amount,due,category:$('#billCategory').value,frequency:$('#billFrequency').value,paid:$('#billPaid').checked};store.mutate(d=>{const i=d.bills.findIndex(x=>x.id===bill.id);if(i>=0)d.bills[i]=bill;else d.bills.push(bill)});clearBillForm();renderMoney();toast(id?'Bill updated.':'Bill added.')}
function clearBillForm(){clearFields(['#billEditId','#billName','#billAmount','#billDue']);if($('#billCategory'))$('#billCategory').value='Housing';if($('#billFrequency'))$('#billFrequency').value='Monthly';if($('#billPaid'))$('#billPaid').checked=false;$('#addBill').textContent='Save Bill'}
function renderMoney(){const st=store.get(),billTotal=st.bills.reduce((a,b)=>a+Number(b.amount||0),0),cash=Number(st.checking)+Number(st.savings)+Number(st.otherAssets||0),projected=cash-billTotal,surplus=Number(st.monthlyIncome||0)-billTotal,netWorth=cash-Number(st.debts||0);setText('#moneyAvailable',usd(cash));setText('#moneyBillsTotal',usd(billTotal));setText('#moneyProjected',usd(projected));setText('#moneySurplus',usd(surplus));setText('#billCount',`${st.bills.length} bill${st.bills.length===1?'':'s'}`);renderBills(st);renderSavings(st);renderFunds(st);renderInsights(st,{billTotal,cash,projected,surplus,netWorth});drawCashflow(st.monthlyIncome||0,billTotal,surplus)}
const usd=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0);
const setText=(sel,text)=>{const el=$(sel);if(el)el.textContent=text};
function renderBills(st){const list=$('#billList');if(!list)return;const bills=[...st.bills].sort((a,b)=>String(a.due).localeCompare(String(b.due)));list.innerHTML=bills.length?bills.map(b=>`<article class="bill-row ${b.paid?'paid':''}"><div class="bill-date"><span>${new Date(b.due+'T12:00:00').toLocaleDateString('en-US',{month:'short'})}</span><b>${new Date(b.due+'T12:00:00').getDate()}</b></div><div class="bill-info"><div class="row wrap"><strong>${escapeHTML(b.name)}</strong><span class="pill">${escapeHTML(b.category||'Other')}</span>${b.paid?'<span class="pill paid-pill">Paid</span>':''}</div><small>${escapeHTML(b.frequency||'Monthly')} · due ${formatDate(b.due)}</small></div><div class="bill-actions"><b>${usd(b.amount)}</b><div><button class="text-button" data-edit-bill="${b.id}">Edit</button><button class="text-button danger-text" data-del-bill="${b.id}">Delete</button></div></div></article>`).join(''):'<div class="status">No bills yet. Add the first one above.</div>';all('[data-edit-bill]').forEach(btn=>btn.onclick=()=>{const b=st.bills.find(x=>x.id==btn.dataset.editBill);if(!b)return;$('#billEditId').value=b.id;$('#billName').value=b.name;$('#billAmount').value=b.amount;$('#billDue').value=b.due;$('#billCategory').value=b.category||'Other';$('#billFrequency').value=b.frequency||'Monthly';$('#billPaid').checked=!!b.paid;$('#addBill').textContent='Update Bill';$('#billName').scrollIntoView({behavior:'smooth',block:'center'})});all('[data-del-bill]').forEach(btn=>btn.onclick=()=>{store.mutate(d=>d.bills=d.bills.filter(x=>x.id!=btn.dataset.delBill));renderMoney();toast('Bill removed.')})}
function renderSavings(st){const list=$('#savingGoalList');if(!list)return;list.innerHTML=st.savingsGoals.length?st.savingsGoals.map(g=>goalCard(g,'goal')).join(''):'<div class="status">Your first savings goal will appear here.</div>';bindGoalActions('goal',st.savingsGoals)}
function renderFunds(st){const list=$('#sinkingFundList');if(!list)return;list.innerHTML=st.sinkingFunds.length?st.sinkingFunds.map(g=>goalCard(g,'fund')).join(''):'<div class="status">Create funds for predictable future expenses.</div>';bindGoalActions('fund',st.sinkingFunds)}
function goalCard(g,type){const pct=Math.max(0,Math.min(100,Math.round(Number(g.current||0)/Math.max(1,Number(g.target||1))*100))),complete=pct>=100;return `<article class="vault-card ${complete?'complete':''}"><div class="vault-glow"></div><div class="row wrap"><div><div class="mini">${type==='fund'?'Sinking fund':'Savings goal'}</div><h4>${complete?'🏆 ':type==='fund'?'🔐 ':'✨ '}${escapeHTML(g.name)}</h4></div><strong>${pct}%</strong></div><div class="liquid-progress"><span style="width:${pct}%"></span></div><div class="row wrap"><span>${usd(g.current)} of ${usd(g.target)}</span>${g.date?`<small>Target ${formatDate(g.date)}</small>`:''}</div><div class="goal-contribute"><input class="input" data-contribution="${type}:${g.id}" type="number" step="0.01" placeholder="Add amount"><button class="btn compact" data-add-contribution="${type}:${g.id}">Contribute</button><button class="text-button danger-text" data-delete-goal="${type}:${g.id}">Remove</button></div></article>`}
function bindGoalActions(type,items){all(`[data-add-contribution^="${type}:"]`).forEach(btn=>btn.onclick=()=>{const [,id]=btn.dataset.addContribution.split(':'),input=$(`[data-contribution="${type}:${id}"]`),amount=Number(input.value)||0;if(amount<=0)return toast('Enter an amount to contribute.');store.mutate(d=>{const arr=type==='fund'?d.sinkingFunds:d.savingsGoals,g=arr.find(x=>x.id==id);if(g){const before=Number(g.current||0);g.current=Math.min(Number(g.target),before+amount);if(before<g.target&&g.current>=g.target)d.wins.unshift({date:new Date().toISOString(),text:`Completed ${g.name} ${type==='fund'?'sinking fund':'savings goal'} 🏆`})}});renderMoney();toast('Contribution added.')});all(`[data-delete-goal^="${type}:"]`).forEach(btn=>btn.onclick=()=>{const [,id]=btn.dataset.deleteGoal.split(':');store.mutate(d=>{if(type==='fund')d.sinkingFunds=d.sinkingFunds.filter(x=>x.id!=id);else d.savingsGoals=d.savingsGoals.filter(x=>x.id!=id)});renderMoney();toast('Goal removed.')})}
function renderInsights(st,m){const el=$('#moneyInsights');if(!el)return;const savingsRate=Number(st.monthlyIncome)>0?Math.max(0,Math.round((Number(st.monthlyIncome)-m.billTotal)/Number(st.monthlyIncome)*100)):0,next=[...st.bills].filter(b=>!b.paid&&b.due>=new Date().toISOString().slice(0,10)).sort((a,b)=>a.due.localeCompare(b.due))[0],funded=st.savingsGoals.filter(g=>Number(g.current)>=Number(g.target)).length;el.innerHTML=`<div class="insight"><span>💎</span><div><b>Net worth</b><p>${usd(m.netWorth)} across listed assets and debts.</p></div></div><div class="insight"><span>${m.surplus>=0?'🌱':'⚠️'}</span><div><b>${m.surplus>=0?'Positive monthly margin':'Monthly gap detected'}</b><p>${m.surplus>=0?`${usd(m.surplus)} remains after listed bills.`:`Listed bills exceed monthly income by ${usd(Math.abs(m.surplus))}.`}</p></div></div><div class="insight"><span>📅</span><div><b>Next bill</b><p>${next?`${escapeHTML(next.name)} · ${usd(next.amount)} on ${formatDate(next.due)}`:'Nothing upcoming is currently listed.'}</p></div></div><div class="insight"><span>🏆</span><div><b>Goal momentum</b><p>${funded} completed · ${st.savingsGoals.length-funded} currently building · estimated margin ${savingsRate}%.</p></div></div>`}
function drawCashflow(income,bills,surplus){const c=$('#cashflowCanvas');if(!c)return;const ratio=window.devicePixelRatio||1,width=c.clientWidth||500,height=250;c.width=width*ratio;c.height=height*ratio;const ctx=c.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,width,height);const vals=[Math.max(0,Number(income)),Math.max(0,Number(bills)),Math.max(0,Number(surplus))],labels=['Income','Bills','Remaining'],max=Math.max(1,...vals),barW=Math.min(78,width/6),gap=(width-barW*3)/4;vals.forEach((v,i)=>{const h=v/max*150,x=gap+i*(barW+gap),y=195-h,g=ctx.createLinearGradient(0,y,0,195);g.addColorStop(0,i===1?'#d98787':i===2?'#78947f':'#efd98d');g.addColorStop(1,i===1?'#7f3434':i===2?'#355642':'#8a6414');ctx.fillStyle=g;roundRect(ctx,x,y,barW,h,14);ctx.fill();ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--ink').trim()||'#241f18';ctx.font='600 12px sans-serif';ctx.textAlign='center';ctx.fillText(labels[i],x+barW/2,220);ctx.fillText(usd(v),x+barW/2,Math.max(15,y-8))})}
function roundRect(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function formatDate(v){if(!v)return '—';return new Date(v+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

export function business(){
  const render=(payload,stale=false)=>{
    const categories=payload?.categories||{},summary=buildExecutiveSummary(categories),updated=payload?.updatedAt;
    $('#pulseUpdated').textContent=updated?`${stale?'Cached · ':''}Updated ${new Date(updated).toLocaleString()}`:'No briefing yet';
    $('#pulseHeroTitle').textContent=summary[0]?.title||'No headlines are available right now.';
    $('#pulseHeroText').textContent=summary.length?`${summary.length} priority signals surfaced across your selected intelligence channels.`:'Pulse will keep the last successful briefing available for you.';
    $('#pulseState').innerHTML=`<span class="pulse-orb"></span><b>${stale?'Offline briefing':'Briefing ready'}</b><small>${payload?.source==='secure-endpoint'?'Secure endpoint':payload?.source==='gdelt-public'?'Live public feed':'Local cache'}</small>`;
    $('#pulseSummary').innerHTML=summary.length?summary.slice(0,3).map(x=>`<article class="card summary-story"><span class="pill">${escapeHTML(x.topic)}</span><a href="${escapeHTML(x.url)}" target="_blank" rel="noopener"><h3>${escapeHTML(x.title)}</h3></a><p>${escapeHTML(x.why)}</p><small>${escapeHTML(x.source)}</small></article>`).join(''):'';
    all('[data-pulse-topic]').forEach(card=>{const topic=card.dataset.pulseTopic,items=categories[topic]||[];card.querySelector('.pill').textContent=items.length?`${items.length} stories`:'Unavailable';card.querySelector('.pulse-skeleton')?.remove();const old=card.querySelector('.pulse-list');if(old)old.remove();card.insertAdjacentHTML('beforeend',`<div class="pulse-list">${items.length?items.slice(0,5).map(a=>`<div class="headline"><a href="${escapeHTML(a.url)}" target="_blank" rel="noopener"><b>${escapeHTML(a.title)}</b></a><small>${escapeHTML(a.source)}${a.publishedAt?` · ${formatNewsDate(a.publishedAt)}`:''}</small></div>`).join(''):'<div class="pulse-empty">No stories returned for this channel.</div>'}</div>`)});
  };
  const refresh=async()=>{const btn=$('#refreshPulse');btn.disabled=true;btn.textContent='Gathering…';$('#pulseState').innerHTML='<span class="pulse-orb"></span><b>Gathering intelligence</b><small>Checking every channel</small>';try{const payload=await loadNews();store.set({pulseCache:payload});render(payload);toast('Pulse briefing refreshed.')}catch(err){const cached=store.get().pulseCache;if(cached?.updatedAt){render(cached,true);toast('Live feed unavailable. Showing cached briefing.')}else{$('#pulseHeroTitle').textContent='The live feed could not be reached.';$('#pulseHeroText').textContent='Check your connection or configure the secure endpoint in config.js.';$('#pulseHero').classList.add('pulse-error');toast('Pulse could not refresh.')}}finally{btn.disabled=false;btn.textContent='Refresh briefing'}};
  const cached=store.get().pulseCache;if(cached?.updatedAt)render(cached,!navigator.onLine);else refresh();$('#refreshPulse').onclick=refresh;
}
function formatNewsDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?'Recent':d.toLocaleDateString('en-US',{month:'short',day:'numeric'})}

export function wellness(){$('#waterPlus').onclick=()=>store.mutate(d=>d.water=Math.min(8,d.water+1));$('#waterReset').onclick=()=>store.set({water:0});$('#saveGym').onclick=()=>store.set({gymMinutes:+$('#gymMinutes').value||0})}
export function journal(){let p=freshPrompt(activePrompt);$('#journalPrompt').textContent=p;all('.prompt-category').forEach(b=>b.onclick=()=>{activePrompt=b.dataset.category;$('#promptCategory').textContent=activePrompt;$('#journalPrompt').textContent=freshPrompt(activePrompt)});$('#saveJournal').onclick=()=>{const text=$('#journalText').value.trim();if(!text)return;store.mutate(d=>d.journalEntries.unshift({date:new Date().toISOString().slice(0,10),category:activePrompt,prompt:$('#journalPrompt').textContent,text}));renderJournalTimeline();$('#journalText').value=''};$('#micButton').onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('Voice dictation is not supported in this browser.');const r=new R();r.interimResults=true;r.onresult=e=>{$('#journalText').value=[...e.results].map(x=>x[0].transcript).join(' ')};r.start()};renderJournalTimeline()}
function renderJournalTimeline(){$('#journalTimeline').innerHTML=store.get().journalEntries.map(x=>`<div class="entry"><div class="mini">${x.date} · ${x.category}</div><b>${x.prompt}</b><p>${x.text}</p></div>`).join('')}
export function goals(){renderGoals();$('#addGoal').onclick=()=>{if(!$('#goalName').value||store.get().goals.length>=25)return;store.mutate(d=>d.goals.push({id:Date.now(),name:$('#goalName').value,category:$('#goalCategory').value,progress:0}));renderGoals()}}
function renderGoals(){$('#goalBoard').innerHTML=store.get().goals.map(g=>`<article class="card gradient-card"><span class="pill">${g.category}</span><h3>${g.name}</h3><input data-goal="${g.id}" type="range" min="0" max="100" value="${g.progress}"><div class="bar"><span style="width:${g.progress}%"></span></div><b>${g.progress}%</b></article>`).join('');all('[data-goal]').forEach(i=>i.oninput=()=>{store.mutate(d=>{const g=d.goals.find(x=>x.id==i.dataset.goal);g.progress=+i.value});renderGoals()})}
export function progress(){
  const s=store.get(),vals={Goals:s.goals.length?Math.round(s.goals.reduce((a,g)=>a+Number(g.progress||0),0)/s.goals.length):0,Wellness:Math.min(100,Math.round(s.water/8*55+Math.min(s.gymMinutes,60)/60*45)),Money:Math.max(0,Math.min(100,Math.round((Number(s.checking)+Number(s.savings)-s.bills.reduce((a,b)=>a+Number(b.amount||0),0))/Math.max(1,Number(s.checking)+Number(s.savings))*100))),Journal:Math.min(100,s.journalEntries.length*5)};
  const wins=[...s.wins,...s.goals.filter(g=>Number(g.progress)>=100).map(g=>({date:new Date().toISOString(),text:`Completed 25 Hard goal: ${g.name} 🏆`}))];
  $('#wins').innerHTML=wins.length?wins.slice(0,8).map(w=>`<div class="entry"><div class="mini">${w.date?new Date(w.date).toLocaleDateString():'Milestone'}</div><b>${escapeHTML(w.text)}</b></div>`).join(''):'<p class="muted">Wins appear automatically as you use the OS.</p>';
  const milestones=[...s.goals.map(g=>({label:g.name,value:Number(g.progress||0),type:g.category||'Goal'})),...s.savingsGoals.map(g=>({label:g.name,value:Math.min(100,Math.round(Number(g.current||0)/Math.max(1,Number(g.target||1))*100)),type:'Savings'}))].sort((a,b)=>b.value-a.value).slice(0,8);
  $('#milestoneTimeline').innerHTML=milestones.length?milestones.map(m=>`<div class="timeline-row"><span class="timeline-dot"></span><div><b>${escapeHTML(m.label)}</b><small>${escapeHTML(m.type)} · ${m.value}% complete</small><div class="bar"><span style="width:${m.value}%"></span></div></div></div>`).join(''):'<div class="status">Add goals or savings targets to build your timeline.</div>';
  const activity=[];for(let i=27;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);let score=0;if(s.journalEntries.some(x=>x.date===key))score++;if(s.calendar[key])score++;if(i===0&&s.water>0)score++;if(i===0&&s.gymMinutes>0)score++;activity.push({key,score})}$('#activityHeatmap').innerHTML=activity.map(x=>`<span title="${x.key}" data-level="${Math.min(4,x.score)}"></span>`).join('');
  const c=$('#progressCanvas'),ctx=c.getContext('2d'),ratio=window.devicePixelRatio||1,width=c.clientWidth||500,height=260;c.width=width*ratio;c.height=height*ratio;ctx.scale(ratio,ratio);const entries=Object.entries(vals),cw=width/(entries.length*1.6);entries.forEach(([k,v],i)=>{const x=(i*1.6+.3)*cw,bh=v/100*190,g=ctx.createLinearGradient(0,220-bh,0,220);g.addColorStop(0,'#efd98d');g.addColorStop(1,'#76571d');ctx.fillStyle=g;roundRect(ctx,x,220-bh,cw,bh,12);ctx.fill();ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--ink');ctx.font='12px sans-serif';ctx.textAlign='left';ctx.fillText(k,x,242);ctx.fillText(v+'%',x,210-bh)})
}

export function premium(){
  all('[data-theme-choice]').forEach(btn=>btn.onclick=()=>{store.set({theme:btn.dataset.themeChoice});toast(`${btn.querySelector('strong').textContent} applied.`)});
  const saveDesign=()=>store.set({design:{motion:$('#motionSelect').value,cards:$('#cardSelect').value,radius:$('#radiusSelect').value,texture:$('#textureSelect').value,type:$('#typeSelect').value}});
  ['motionSelect','cardSelect','radiusSelect','textureSelect','typeSelect'].forEach(id=>$('#'+id).onchange=saveDesign);
  $('#exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([store.export()],{type:'application/json'}));a.download=`key-collective-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();toast('Verified backup created.')};
  $('#importData').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{store.import(r.result);toast('Backup imported. Reloading…');setTimeout(()=>location.reload(),500)}catch(err){toast(err.message||'Invalid backup file.')}};r.readAsText(file)};
  $('#recoverData').onclick=()=>{try{if(store.recover()){toast('Previous save restored. Reloading…');setTimeout(()=>location.reload(),500)}else toast('No recovery copy is available yet.')}catch{toast('Recovery could not be completed.')}};
  $('#downloadDiagnostic').onclick=()=>{const report={generatedAt:new Date().toISOString(),online:navigator.onLine,userAgent:navigator.userAgent,storageKey:store.key,validation:store.validate(),theme:store.get().theme,design:store.get().design,counts:{bills:store.get().bills.length,calendarDays:Object.keys(store.get().calendar).length,journalEntries:store.get().journalEntries.length,goals:store.get().goals.length,laniPhotos:store.get().laniPhotos.length}};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download='key-collective-diagnostic.json';a.click()};
}
export function profile(){
  const save=(valuesOnly=false)=>{const current=store.get().profile||{};const values=$('#profileValues').value.split(',').map(v=>v.trim()).filter(Boolean).slice(0,10);store.set({profile:valuesOnly?{...current,values}:{...current,name:$('#profileName').value.trim()||'Alexis',title:$('#profileTitle').value.trim(),mission:$('#profileMission').value.trim(),vision:$('#profileVision').value.trim(),annualTheme:$('#profileAnnualTheme').value.trim(),fiveYearVision:$('#profileFiveYear').value.trim(),legacy:$('#profileLegacy').value.trim(),values}});toast(valuesOnly?'Core values updated.':'Your blueprint is saved.')};
  $('#saveProfile').onclick=()=>save(false);$('#saveValues').onclick=()=>save(true);
}
