import {store} from './store.js';
import {getPhotos,deletePhoto} from './photo-db.js';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2100)};
const fireworks=(mini=false)=>{const layer=document.createElement('div');layer.className=mini?'mini-fireworks':'lux-fireworks';layer.innerHTML=Array.from({length:mini?10:34},(_,i)=>`<i style="--i:${i};--x:${Math.random()*100}%;--d:${Math.random()*1.2}s"></i>`).join('');document.body.append(layer);setTimeout(()=>layer.remove(),mini?900:2200)};
export function patchPagesSprint6B(pages){
 const oldMoney=pages.money;pages.money=()=>oldMoney()+`<section class="card cash-command"><div class="section-title"><div><div class="eyebrow">Today’s money command</div><h2>Give every dollar a job.</h2></div><span class="pill">Sprint 6B</span></div><div class="cash-grid"><label>Available cash<input id="availableCash" type="number" min="0" step=".01" value="${Number(store.get().financial?.availableCash||0)}"></label><label>Last paycheck<input id="lastPaycheck" type="number" min="0" step=".01" value="${Number(store.get().financial?.lastPaycheck||0)}"></label><label>Next paycheck<input id="nextPaycheck" type="number" min="0" step=".01" value="${Number(store.get().financial?.nextPaycheck||0)}"></label><label>Expected date<input id="nextPaycheckDate" type="date" value="${esc(store.get().financial?.nextPaycheckDate||'')}"></label></div><button id="saveCashCommand" class="btn">Save cash position</button><div id="cashSummary" class="cash-summary"></div></section>`;
 const oldJournal=pages.journal;pages.journal=()=>oldJournal()+`<dialog id="reflectionDialog" class="reflection-dialog"><article class="card"><button id="closeReflection" class="icon-button reflection-close">×</button><div id="reflectionFull"></div></article></dialog>`;
}
export async function enhanceSprint6B(id,router){
 if(id==='dashboard')focusFix();if(id==='lani')await laniFix();if(id==='wellness')wellnessFix();if(id==='money')moneyFix();if(id==='journal')reflectionFix();if(id==='premium')designFix();if(id==='goals')hardFix();
}
function focusFix(){all('[data-top3]').forEach(c=>{c.onchange=e=>{const y=scrollY,i=+c.dataset.top3;store.mutate(d=>{d.top3Done[i]=c.checked;if(d.priorityDetails?.[i])d.priorityDetails[i].progress=c.checked?100:0});requestAnimationFrame(()=>scrollTo(0,y));const done=store.get().top3Done.filter(Boolean).length;if(done===3)fireworks(false);else if(c.checked)fireworks(true)}});const card=$('.executive-focus-card');if(card&&store.get().top3Done.every(Boolean)){new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)fireworks(true)}),{threshold:.7}).observe(card)}}
async function laniFix(){const photos=await getPhotos(),stage=$('#laniSlideshow'),thumbs=$('#laniThumbs');if(!stage||!thumbs)return;let idx=Math.max(0,photos.length-1),timer;const urls=photos.map(p=>({...p,url:URL.createObjectURL(p.blob)}));const show=()=>{if(!urls.length)return;stage.innerHTML=`<img class="active" src="${urls[idx].url}" alt="Lani memory"><button id="laniPrev" class="lani-arrow prev" aria-label="Previous photo">←</button><button id="laniNext" class="lani-arrow next" aria-label="Next photo">→</button>`;$('#laniPrev').onclick=()=>{idx=(idx-1+urls.length)%urls.length;show();restart()};$('#laniNext').onclick=()=>{idx=(idx+1)%urls.length;show();restart()}};const restart=()=>{clearInterval(timer);if(urls.length>1)timer=setInterval(()=>{idx=(idx+1)%urls.length;show()},5000)};show();restart();all('[data-vault-photo]').forEach(b=>{b.onclick=async e=>{e.preventDefault();e.stopPropagation();if(e.target.closest('span')){await deletePhoto(b.dataset.vaultPhoto);toast('Photo removed.');await laniFix();return}idx=Math.max(0,urls.findIndex(x=>x.id===b.dataset.vaultPhoto));show();restart()}});const share=$('#shareLaniSnapshot');if(share)share.classList.add('contrast-safe')}
function wellnessFix(){const render=()=>{const s=store.get(),n=$('.metric');if($('#waterPlus'))$('#waterPlus').onclick=()=>{const y=scrollY;store.mutate(d=>d.water=Math.min(8,(d.water||0)+1));const val=store.get().water;const head=[...document.querySelectorAll('*')].find(x=>x.childNodes.length===1&&x.textContent.trim().match(/^\d+\/8$/));if(head)head.textContent=`${val}/8`;toast('Water saved.');requestAnimationFrame(()=>scrollTo(0,y));if(val===8)fireworks(true)};$('#saveWellness')?.addEventListener('click',()=>{});const btn=[...all('button')].find(b=>/save wellness check-in/i.test(b.textContent));if(btn)btn.onclick=()=>{const movement=+$('input[id*="gym"], input[placeholder*="Movement"], input[type="number"]')?.value||0;const nums=all('input[type="number"]');const sleep=+(nums[1]?.value||0);store.mutate(d=>{d.gymMinutes=movement;d.wellness=d.wellness||{};d.wellness.sleep=sleep;d.wellness.history=d.wellness.history||[];d.wellness.history.push({date:new Date().toISOString(),movement,sleep,mood:$('select')?.value||'Steady'})});toast('Wellness check-in saved.');fireworks(true)}};render()}
function moneyFix(){const draw=()=>{const s=store.get(),f=s.financial||{},bills=s.bills.reduce((a,b)=>a+(b.paid?0:Number(b.amount||0)),0),left=Number(f.availableCash||0)-bills;$('#cashSummary').innerHTML=`<div><small>Available today</small><strong>$${Number(f.availableCash||0).toFixed(2)}</strong></div><div><small>Unpaid bills</small><strong>$${bills.toFixed(2)}</strong></div><div><small>Safe to assign</small><strong>$${left.toFixed(2)}</strong></div>`};$('#saveCashCommand').onclick=()=>{store.mutate(d=>{d.financial={...(d.financial||{}),availableCash:+$('#availableCash').value||0,lastPaycheck:+$('#lastPaycheck').value||0,nextPaycheck:+$('#nextPaycheck').value||0,nextPaycheckDate:$('#nextPaycheckDate').value}});draw();toast('Cash position saved.');fireworks(true)};const update=[...all('button')].find(b=>/update forecast/i.test(b.textContent));if(update)update.onclick=()=>{const income=+all('input[type="number"]')[0]?.value||0,spend=+all('input[type="number"]')[1]?.value||0;store.mutate(d=>{d.monthlyIncome=income;d.financial={...(d.financial||{}),monthlySpending:spend}});toast('Forecast updated in place.');requestAnimationFrame(draw)};draw()}
function reflectionFix(){const dialog=$('#reflectionDialog'),full=$('#reflectionFull');all('#s5JournalArchive .entry').forEach((e,i)=>{e.tabIndex=0;e.setAttribute('role','button');e.onclick=()=>{const r=store.get().journalEntries[i];if(!r)return;full.innerHTML=`<div class="eyebrow">${esc(r.date)} · ${esc(r.category)}</div><h2>${esc(r.prompt||'Reflection')}</h2><p class="reflection-body">${esc(r.text)}</p><div class="row"><button class="btn ghost" id="deleteReflection">Delete</button></div>`;dialog.showModal();$('#deleteReflection').onclick=()=>{store.mutate(d=>d.journalEntries=d.journalEntries.filter(x=>x.id!==r.id));dialog.close();toast('Reflection deleted.')}};e.onkeydown=x=>{if(x.key==='Enter')e.click()}});$('#closeReflection')?.addEventListener('click',()=>dialog.close())}
function designFix(){all('[data-s5-theme]').forEach(b=>b.onclick=()=>{store.set({theme:b.dataset.s5Theme});all('[data-s5-theme]').forEach(x=>x.classList.toggle('selected',x===b));toast(`${b.querySelector('strong')?.textContent||'Theme'} applied.`)});all('[data-design-pack]').forEach(b=>b.onclick=()=>{store.mutate(d=>{d.design={...(d.design||{}),pack:b.dataset.designPack,type:b.dataset.designPack}});all('[data-design-pack]').forEach(x=>x.classList.toggle('selected',x===b));toast('Typography pack applied.')} );const buttons=all('.preview-room .btn');buttons.forEach((b,i)=>b.onclick=()=>{b.classList.add('is-pressed','is-loading');setTimeout(()=>{b.classList.remove('is-loading');b.classList.add('is-success');b.textContent=i?'Secondary complete ✓':'Primary complete ✓';fireworks(true)},650);setTimeout(()=>{b.classList.remove('is-pressed','is-success');b.textContent=i?'Secondary action':'Primary action'},1700)});const tex=$('#s5Texture');if(tex)tex.onchange=()=>{store.mutate(d=>d.design={...(d.design||{}),texture:tex.value});toast(tex.value==='linen'?'Coastal Linen applied.':'Texture applied.')}}
function hardFix(){const board=$('#hardBoard');if(!board)return;all('[data-hard-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.hardView;store.set({hardView:v});board.className=`hard-board ${v==='list'?'list-view':'grid-view'}`;all('[data-hard-view]').forEach(x=>x.classList.toggle('active',x===b));toast(`${v==='list'?'List':'Grid'} view applied.`)});all('[data-hard-complete]').forEach(b=>b.addEventListener('click',()=>fireworks(true)))}
