import {store} from './store.js';
import {putPhoto,getPhotos,deletePhoto} from './photo-db.js';
const $=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000)};
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
export function patchPages(pages){
 const wrap=(id,fn)=>{const old=pages[id];pages[id]=()=>fn(old())};
 wrap('money',html=>{const extra=`<article class="card bill-import-card"><div class="section-title"><div><div class="eyebrow">Fast setup</div><h3>Bulk Bill Import</h3></div><span class="pill">Paste once</span></div><p>Paste CSV or tab-separated rows: <b>Name, Amount, Due Date, Clear Date, Category, Frequency</b>.</p><textarea id="billBulkInput" rows="7" placeholder="Apple Card,125.40,2026-07-28,2026-07-29,Credit Card,Monthly"></textarea><div class="row wrap"><button id="importBills" class="btn">Import bills</button><button id="downloadBillTemplate" class="btn ghost">Download template</button></div><div id="billImportStatus" class="status">Imported bills flow into Dashboard, Morning Brief, and Agenda.</div></article>`;const i=html.lastIndexOf('</div>');return html.slice(0,i)+extra+html.slice(i)});
 wrap('intelligence',html=>html.replace('<div class="intelligence-grid">',`<article class="card morning-routine-card"><div class="section-title"><div><div class="eyebrow">Power on gently</div><h3>Morning Routine</h3></div><span class="pill" id="routineScore">0 of 7</span></div><div id="morningRoutine" class="routine-grid"></div></article><div class="intelligence-grid">`));
 wrap('career',html=>html.replace('</section>`','</section>`'));
}
export async function enhanceSprint4(id,router){
 all('[data-jump]').forEach(b=>b.onclick=()=>router.go(b.dataset.jump));
 if(id==='profile')profile();
 if(id==='dashboard')dashboard();
 if(id==='intelligence')morning();
 if(id==='calendar')agenda();
 if(id==='lani')await lani();
 if(id==='money')money();
 if(id==='journal')journal();
 if(id==='goals')goals();
 if(id==='career')career();
}
function profile(){
 const name=$('#profileName');if(name&&!name.value)name.value='Keyona';
 $('#saveProfileQuick')?.addEventListener('click',()=>{const quick={};all('[data-profile-quick]').forEach(i=>quick[i.dataset.profileQuick]=i.value.trim());store.mutate(d=>{d.profile.name=d.profile.name||'Keyona';d.profile.quickInfo=quick});toast('Quick info saved.')});
}
function dashboard(){
 const st=store.get(),cap=st.laniFeaturedCaption||smartCaption(st.laniMemories?.[0]?.text);const box=$('#dashboardLaniCaption');if(box)box.innerHTML=`<div class="mini">Today’s little moment</div><p>${esc(cap)}</p>`;
 loadDashboardPhoto();
}
async function loadDashboardPhoto(){try{const photos=await getPhotos();const box=$('#dashboardLani');if(!box||!photos.length)return;const featured=photos.find(p=>p.featured)||photos.at(-1);const url=URL.createObjectURL(featured.blob);box.innerHTML=`<img src="${url}" class="dashboard-lani-photo" alt="Lani memory">`}catch{}}
function smartCaption(text=''){const t=text.toLowerCase();if(t.includes('school'))return 'Tiny backpack. Huge dreams. A brand-new chapter is officially in session. 🎒';if(t.includes('pool')||t.includes('swim'))return 'Splash report: confidence growing one brave little ripple at a time. 💦';if(t.includes('park'))return 'Today’s mission: conquer every slide and collect every smile. 🌳';return 'Small moment, enormous personality—the kind of memory that quietly becomes everything. ✨'}
function morning(){const labels={water:'Drink the first glass of water',teeth:'Brush teeth',face:'Wash face + skincare',bed:'Make the bed',dressed:'Get dressed for the day',calendar:'Review Agenda + upcoming bills',top3:'Confirm today’s Top Three'};const draw=()=>{const st=store.get(),r=st.morningRoutine||{},done=Object.keys(labels).filter(k=>r[k]).length;$('#routineScore').textContent=`${done} of ${Object.keys(labels).length}`;$('#morningRoutine').innerHTML=Object.entries(labels).map(([k,v])=>`<label class="routine-item"><input type="checkbox" data-routine="${k}" ${r[k]?'checked':''}><span>${v}</span></label>`).join('');all('[data-routine]').forEach(i=>i.onchange=()=>store.mutate(d=>{d.morningRoutine=d.morningRoutine||{};d.morningRoutine[i.dataset.routine]=i.checked}))};draw()}
function agenda(){
 const detail=$('#selectedDayDetail');all('[data-day]').forEach(day=>day.addEventListener('click',()=>showDay(day.dataset.day,detail)));
 const save=$('#saveCalendarDay');if(save)save.onclick=()=>{const date=$('#calDate').value;if(!date)return toast('Choose a date.');store.mutate(d=>d.calendar[date]={subject:$('#calSubject').value,events:$('#calEvents').value,tasks:$('#calTasks').value,birthdays:$('#calBirthdays').value,holidays:$('#calHolidays').value,notes:$('#calNotes').value});toast('Day saved.');setTimeout(()=>location.reload(),250)};
 all('[data-agenda-tab]').forEach(btn=>btn.onclick=()=>{all('[data-agenda-tab]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const map={event:'#calEvents',task:'#calTasks',birthday:'#calBirthdays',holiday:'#calHolidays'};$(map[btn.dataset.agendaTab])?.focus()});
 $('#saveCalendarDay')?.addEventListener('click',()=>setTimeout(()=>decorateCalendar(),50));decorateCalendar();
 $('#icsImport')?.addEventListener('change',importICS);$('#icsExport')?.addEventListener('click',exportICS);
}
function decorateCalendar(){const st=store.get();all('[data-day]').forEach(day=>{day.querySelector('.day-dots')?.remove();const key=day.dataset.day,v=st.calendar[key]||{},dots=[];if(v.events?.trim())dots.push('event');if(v.tasks?.trim())dots.push('task');if(v.birthdays?.trim())dots.push('birthday');if(v.holidays?.trim())dots.push('holiday');if(st.bills.some(b=>b.due===key&&!b.paid))dots.push('bill');day.insertAdjacentHTML('beforeend',`<div class="day-dots">${dots.map(x=>`<i class="dot ${x}"></i>`).join('')}</div>`)})}
function showDay(key,el){const st=store.get(),v=st.calendar[key]||{},bills=st.bills.filter(b=>b.due===key),groups=[['Events',v.events],['Tasks',v.tasks],['Birthdays',v.birthdays],['Holidays',v.holidays],['Bills',bills.map(b=>`${b.name} · $${Number(b.amount||0).toFixed(2)}`).join('\n')],['Notes',v.notes]];el.innerHTML=`<h4>${new Date(key+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</h4>`+groups.filter(x=>x[1]?.trim()).map(([h,x])=>`<div class="day-detail-group"><b>${h}</b>${x.split('\n').filter(Boolean).map(i=>`<p>${esc(i)}</p>`).join('')}</div>`).join('')||'<p>Nothing scheduled yet.</p>';}
async function importICS(e){const file=e.target.files[0];if(!file)return;const text=await file.text(),events=[...text.matchAll(/BEGIN:VEVENT([\s\S]*?)END:VEVENT/g)].map(m=>m[1]);let count=0;store.mutate(d=>{events.forEach(block=>{const ds=(block.match(/DTSTART[^:]*:(\d{8})/)||[])[1],sum=(block.match(/SUMMARY:(.*)/)||[])[1];if(!ds||!sum)return;const date=`${ds.slice(0,4)}-${ds.slice(4,6)}-${ds.slice(6,8)}`;d.calendar[date]=d.calendar[date]||{};d.calendar[date].events=[d.calendar[date].events,sum.trim()].filter(Boolean).join('\n');d.calendar[date].subject=d.calendar[date].subject||sum.trim();count++})});toast(`${count} calendar event${count===1?'':'s'} imported.`);setTimeout(()=>location.reload(),400)}
function exportICS(){const st=store.get(),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//The Key Collective OS//Agenda//EN'];Object.entries(st.calendar).forEach(([date,v])=>{const items=(v.events||v.subject||'').split('\n').filter(Boolean);items.forEach((summary,i)=>lines.push('BEGIN:VEVENT',`UID:${date}-${i}@keycollective.local`,`DTSTART;VALUE=DATE:${date.replaceAll('-','')}`,`SUMMARY:${summary.replace(/[\n,;]/g,' ')}`,'END:VEVENT'))});lines.push('END:VCALENDAR');download('keyona-agenda.ics',lines.join('\r\n'),'text/calendar')}
async function lani(){
 const upload=$('#laniUpload'),status=$('#laniUploadStatus');if($('#laniFeaturedCaption'))$('#laniFeaturedCaption').value=store.get().laniFeaturedCaption||'';$('#saveLaniCaption')?.addEventListener('click',()=>{store.set({laniFeaturedCaption:$('#laniFeaturedCaption').value.trim()});toast('Dashboard caption saved.')});
 all('[data-quick-lani]').forEach(b=>b.onclick=()=>{const k=b.dataset.quickLani,current=store.get().laniFacts[k]||'',value=prompt(`Update ${k.replace(/([A-Z])/g,' $1').toLowerCase()}`,current);if(value!==null){store.mutate(d=>d.laniFacts[k]=value.trim());location.reload()}});
 upload.onchange=async e=>{const files=[...e.target.files].slice(0,18);let saved=0,failed=0;status.textContent=`Saving ${files.length} photo${files.length===1?'':'s'}…`;for(const file of files){try{const blob=await resize(file);await putPhoto({id:crypto.randomUUID?.()||`${Date.now()}-${saved}`,blob,name:file.name,createdAt:new Date().toISOString(),featured:false});saved++}catch(err){console.warn(err);failed++}}status.textContent=`${saved} photo${saved===1?'':'s'} added${failed?` · ${failed} could not be saved`:''}.`;await renderVault();e.target.value=''};await migrateLegacy();await renderVault();
}
async function migrateLegacy(){const st=store.get();if(!st.laniPhotos?.length)return;const existing=await getPhotos();if(existing.length)return;for(const [i,url] of st.laniPhotos.entries()){try{const blob=await (await fetch(url)).blob();await putPhoto({id:`legacy-${i}`,blob,name:`Legacy photo ${i+1}`,createdAt:new Date(Date.now()+i).toISOString(),featured:false})}catch{}}store.mutate(d=>{d.laniPhotos=[]})}
async function renderVault(){const photos=await getPhotos(),box=$('#laniSlideshow'),thumbs=$('#laniThumbs');if(!box)return;const urls=photos.map(p=>({...p,url:URL.createObjectURL(p.blob)}));box.innerHTML=urls.length?`<img class="active" src="${urls.at(-1).url}" alt="Lani memory">`:'<div class="lani-empty"><span>📸</span><b>Add photos to begin the dynamic collage.</b></div>';$('#photoCount').textContent=`${urls.length} photo${urls.length===1?'':'s'}`;thumbs.innerHTML=urls.map(p=>`<button class="lani-thumb vault-thumb" data-vault-photo="${p.id}"><img src="${p.url}" alt=""><span>×</span></button>`).join('');all('[data-vault-photo]').forEach(b=>{b.onclick=async ev=>{if(ev.target.tagName==='SPAN'){await deletePhoto(b.dataset.vaultPhoto);await renderVault();return}const p=urls.find(x=>x.id===b.dataset.vaultPhoto);box.innerHTML=`<img class="active" src="${p.url}" alt="Lani memory">`}})}
function resize(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(url);b?resolve(b):reject(new Error('Compression failed'))},'image/jpeg',.82)};img.onerror=reject;img.src=url})}
function money(){
 $('#importBills')?.addEventListener('click',()=>{const raw=$('#billBulkInput').value.trim();if(!raw)return toast('Paste at least one bill.');const rows=raw.split(/\r?\n/).map(line=>line.includes('\t')?line.split('\t'):line.split(',')).filter(r=>r[0]?.trim());let imported=0;store.mutate(d=>{rows.forEach(r=>{const [name,amount,due,clearDate,category='Other',frequency='Monthly']=r.map(x=>x.trim());if(!name||!Number(amount)||!/\d{4}-\d{2}-\d{2}/.test(due))return;d.bills.push({id:crypto.randomUUID?.()||Date.now()+imported,name,amount:Number(amount),due,clearDate,category,frequency,paid:false});imported++})});$('#billImportStatus').textContent=`${imported} bill${imported===1?'':'s'} imported and connected across the OS.`;toast('Bills imported.');setTimeout(()=>location.reload(),450)});
 $('#downloadBillTemplate')?.addEventListener('click',()=>download('keyona-bill-import-template.csv','Name,Amount,Due Date,Clear Date,Category,Frequency\nApple Card,125.40,2026-07-28,2026-07-29,Credit Card,Monthly','text/csv'));
}
function journal(){let history=[];const updateFilters=()=>{const entries=store.get().journalEntries,cats=[...new Set(entries.map(x=>x.category))];$('#journalArchiveFilters').innerHTML=['All',...cats].map(c=>`<button class="btn ghost archive-filter" data-archive="${c}">${c}</button>`).join('');all('[data-archive]').forEach(b=>b.onclick=()=>renderArchive(b.dataset.archive))};const renderArchive=cat=>{const xs=store.get().journalEntries.filter(x=>cat==='All'||x.category===cat);$('#journalTimeline').innerHTML=xs.length?xs.map(x=>`<div class="entry"><div class="mini">${x.date} · ${esc(x.category)}</div><b>${esc(x.prompt)}</b><p>${esc(x.text)}</p></div>`).join(''):'<div class="status">No reflections in this theme yet.</div>'};$('#nextPrompt')?.addEventListener('click',()=>document.querySelector(`.prompt-category[data-category="${$('#promptCategory').textContent}"]`)?.click());$('#previousPrompt')?.addEventListener('click',()=>{if(history.length)$('#journalPrompt').textContent=history.pop()});$('#journalPrompt')?.addEventListener('DOMSubtreeModified',()=>history.push($('#journalPrompt').textContent));setTimeout(updateFilters,0)}
function goals(){const icons={Life:'✦',Money:'◈',Career:'◇',Wellness:'⌁',Family:'♡',Business:'◆'};all('#goalBoard .gradient-card').forEach(card=>{const cat=card.querySelector('.pill')?.textContent||'Life';card.insertAdjacentHTML('afterbegin',`<span class="goal-icon">${icons[cat]||'✦'}</span>`)});}
function career(){const input=$('#academyObjective');if(input)input.value=store.get().academy?.objective||'';$('#saveAcademyObjective')?.addEventListener('click',()=>{store.mutate(d=>{d.academy=d.academy||{};d.academy.objective=input.value.trim()});toast('Learning objective saved.')})}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
