import {store} from './store.js';
import {pages} from './pages.js';
import {getMemos} from './memo-db.js';
import {putEvolutionMedia,getEvolutionMedia,deleteEvolutionMedia} from './evolution-db.js';

const BUILD='Sprint 6B.44.2 Release Hardening';
const $=(s,r=document)=>r.querySelector(s),all=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),v=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${v.year}-${v.month}-${v.day}`};
const monthKey=()=>today().slice(0,7);
const routeLabels={dashboard:'Executive Dashboard',intelligence:'Morning Brief',calendar:'Agenda',lani:'Lani’s Corner',career:'Payments Academy',business:'Executive Intelligence',money:'Financial Studio',wellness:'Wellness Studio',sanctuary:'Sanctuary',journal:'Reflection Garden',goals:'25 Hard',progress:'Growth Studio',premium:'Design + Data',profile:'My Profile'};
const dataRoutes={calendar:'calendar',bills:'money',checking:'money',savings:'money',financial:'money',journalEntries:'journal',journalPromptHistory:'journal',goals:'goals',water:'wellness',gymMinutes:'wellness',wellness:'wellness',sobriety:'wellness',laniFacts:'lani',laniMemories:'lani',careerNotes:'career',academy:'career',pulseCache:'business',savedArticles:'business',intelligenceNotes:'business',sanctuary:'sanctuary',growth:'progress',wins:'progress',profile:'profile'};
const promptGroups={
  'Self-Love':['What part of you deserves tenderness today?','Where are you already enough?','What boundary would feel like self-respect?'],
  Growth:['What are you ready to outgrow?','Which small brave choice is next?','What lesson are you finally ready to use?'],
  Gratitude:['What ordinary thing quietly helped today?','Who made life lighter recently?','What would you miss if it disappeared tomorrow?'],
  Motherhood:['Where did joy show up with Lani today?','What does good-enough motherhood look like today?','What memory from this season deserves saving?'],
  Career:['What payments concept became clearer today?','Which professional win are you undercounting?','What skill deserves focused practice next?'],
  Healing:['What can you release without denying what happened?','What does safety feel like in your life today?','Where can you offer yourself more patience?'],
  Dreams:['Describe the life you are unlocking.','Which dream needs a date, not just hope?','What would ten percent more courage make possible?']
};
let routerRef=null,currentPrompt='',attachment=null;
const go=route=>routerRef?.go?routerRef.go(route):$(`.nav-button[data-route="${route}"]`)?.click();
const pulseStories=state=>Object.entries(state.pulseCache?.categories||{}).flatMap(([topic,items])=>(items||[]).map(item=>({...item,topic})));
const dateLabel=value=>value?new Date(value).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Saved locally';
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value)||0);
const addDays=(date,days)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

function familyDates(year){
  const firstSunday=(month)=>{const d=new Date(year,month,1,12);d.setDate(1+(7-d.getDay())%7);return `${year}-${String(month+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const september=new Date(year,8,1,12),firstMonday=1+(8-september.getDay())%7,grandparents=new Date(year,8,firstMonday+6,12);
  return [
    [`${year}-05-24`,'👬 National Brothers Day'],
    [firstSunday(7),'👭 National Sisters Day'],
    [`${year}-09-${String(grandparents.getDate()).padStart(2,'0')}`,'👵🏽 Grandparents Day'],
    [`${year}-09-25`,'💗 National Daughters Day']
  ];
}
function ensureFamilyObservances(){
  const year=Number(today().slice(0,4)),state=store.get();let changed=false;
  const additions=[...familyDates(year),...familyDates(year+1)];
  for(const [date,label] of additions){const current=String(state.calendar?.[date]?.holidays||'');if(!current.includes(label))changed=true}
  if(!changed)return;
  store.mutate(d=>{d.calendar=d.calendar||{};for(const [date,label] of additions){d.calendar[date]=d.calendar[date]||{};const lines=String(d.calendar[date].holidays||'').split('\n').filter(Boolean);if(!lines.includes(label))d.calendar[date].holidays=[...lines,label].join('\n')}});
}

function paycheckBills(state,start,end){return (state.bills||[]).filter(b=>!b.paid&&b.due&&b.due>=start&&b.due<=end)}
function forecastMarkup(){
  const s=store.get(),saved=s.financial?.paycheckPlanner||{},start=saved.payDate||s.financial?.nextPaycheckDate||today(),end=saved.periodEnd||addDays(start,13),pay=Number(saved.amount??(s.financial?.nextPaycheck||0)),assigned=Number(saved.assignedSavings||0),bills=paycheckBills(s,start,end),owed=bills.reduce((n,b)=>n+Number(b.amount||0),0),after=pay-owed,free=after-assigned;
  return `<section class="card kc44-paycheck" data-kc44-paycheck><div class="section-title"><div><div class="eyebrow">Smart paycheck forecast</div><h3>Give every dollar a job.</h3></div><span class="pill">${bills.length} bill${bills.length===1?'':'s'} in period</span></div><p class="muted">Save the projected paycheck and see exactly what remains after bills and intentional savings.</p><div class="kc44-form-grid"><label>Projected paycheck<input type="number" min="0" step=".01" data-kc44-pay="amount" value="${pay}"></label><label>Pay date<input type="date" data-kc44-pay="payDate" value="${esc(start)}"></label><label>Pay-period end<input type="date" data-kc44-pay="periodEnd" value="${esc(end)}"></label><label>Assign to savings<input type="number" min="0" step=".01" data-kc44-pay="assignedSavings" value="${assigned}"></label></div><button class="btn" data-kc44-action="save-paycheck">Save + update forecast</button><div class="kc44-money-metrics"><div><small>Projected paycheck</small><b>${money(pay)}</b></div><div><small>Bills in pay period</small><b>${money(owed)}</b></div><div><small>Available after bills</small><b>${money(Math.max(0,after))}</b></div><div><small>Assigned savings</small><b>${money(assigned)}</b></div><div><small>Unassigned spending</small><b>${money(Math.max(0,free))}</b></div><div class="${free<0?'is-short':''}"><small>${free<0?'Shortage':'Remaining cushion'}</small><b>${money(Math.abs(free))}</b></div></div><details class="kc44-period-bills"><summary>Bills included in this pay period</summary>${bills.map(b=>`<div class="brief-line"><span>💳</span><div><b>${esc(b.name)}</b><small>${esc(b.due)} · ${money(b.amount)}</small></div></div>`).join('')||'<div class="status">No unpaid bills fall inside this pay period.</div>'}</details></section>`;
}
function renderMoney(){
  if((($('#page h1')?.textContent||'').trim())!=='Financial Studio')return;
  $('#page [data-kc44-paycheck]')?.remove();const legacy=all('#page h2').find(h=>/Give every dollar a job/i.test(h.textContent||''))?.closest('section,article');
  if(legacy){legacy.insertAdjacentHTML('afterend',forecastMarkup());legacy.remove()}
  else{($('#financialControls6B22')||$('#page')).insertAdjacentHTML('beforebegin',forecastMarkup())}
  const list=$('#billList22');if(list&&!list.closest('[data-kc44-bills]')){const details=document.createElement('details');details.className='kc44-bill-drawer';details.dataset.kc44Bills='';details.innerHTML=`<summary>View and manage bills <span class="pill">${all('[data-bill-id]',list).length} total</span></summary><div class="kc44-bill-filters"><button class="btn ghost active" data-kc44-bill-filter="all">All</button><button class="btn ghost" data-kc44-bill-filter="upcoming">Upcoming</button><button class="btn ghost" data-kc44-bill-filter="due">Still Due</button><button class="btn ghost" data-kc44-bill-filter="paid">Paid</button></div>`;list.before(details);details.append(list)}
}

function agendaExtras(date){const value=store.get().calendar?.[date]||{};return {location:value.location||'',mapLink:value.mapLink||'',parking:value.parking||'',contact:value.contact||'',confirmation:value.confirmation||'',prepMinutes:value.prepMinutes||'',leaveTime:value.leaveTime||'',appointmentNotes:value.appointmentNotes||''}}
function agendaConciergeFields(date,prefix='page'){
  const value=agendaExtras(date);
  return `<div class="kc44-agenda-concierge" data-kc44-agenda-fields="${prefix}" data-date="${esc(date)}"><div class="section-title"><div><div class="eyebrow">Appointment concierge</div><h3>Directions + preparation</h3></div><span class="pill">Saved with this day</span></div><div class="kc44-form-grid"><label>Location or address<input class="input" data-kc44-agenda="location" value="${esc(value.location)}" placeholder="Business name or full address"></label><label>Saved Google Maps link<input class="input" data-kc44-agenda="mapLink" value="${esc(value.mapLink)}" placeholder="Optional shared Maps link"></label><label>Parking or entrance instructions<input class="input" data-kc44-agenda="parking" value="${esc(value.parking)}" placeholder="Where to park or enter"></label><label>Contact information<input class="input" data-kc44-agenda="contact" value="${esc(value.contact)}" placeholder="Name or phone number"></label><label>Confirmation number<input class="input" data-kc44-agenda="confirmation" value="${esc(value.confirmation)}"></label><label>Preparation time (minutes)<input class="input" type="number" min="0" step="5" data-kc44-agenda="prepMinutes" value="${esc(value.prepMinutes)}"></label><label>Leave by<input class="input" type="time" data-kc44-agenda="leaveTime" value="${esc(value.leaveTime)}"></label><label>Appointment notes<input class="input" data-kc44-agenda="appointmentNotes" value="${esc(value.appointmentNotes)}"></label></div><div class="row wrap"><button class="btn" type="button" data-kc44-action="save-agenda-extras" data-prefix="${prefix}">Save preparation details</button><button class="btn ghost" type="button" data-kc44-action="open-google-directions" data-prefix="${prefix}">Open Google Maps</button><button class="btn ghost" type="button" data-kc44-action="open-apple-directions" data-prefix="${prefix}">Open Apple Maps</button><button class="btn secondary" type="button" data-kc44-action="export-apple-day" data-prefix="${prefix}">Add day to Apple Calendar</button></div><div class="status" data-kc44-agenda-status>Directions and preparation details stay private on this device.</div></div>`;
}
function smartAgendaItems(){
  const s=store.get(),start=today(),end=addDays(start,7),items=[];
  Object.entries(s.calendar||{}).forEach(([date,day])=>{if(date<start||date>end)return;[['Event',day.events],['Task',day.tasks],['Birthday',day.birthdays],['Holiday',day.holidays]].forEach(([type,value])=>String(value||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean).forEach(label=>items.push({date,type,label,location:day.location||'',leaveTime:day.leaveTime||''})))});
  (s.bills||[]).filter(b=>!b.paid&&b.due>=start&&b.due<=end).forEach(b=>items.push({date:b.due,type:'Bill',label:b.name,amount:Number(b.amount)||0}));
  return items.sort((a,b)=>a.date.localeCompare(b.date)||String(a.leaveTime||'').localeCompare(String(b.leaveTime||'')));
}
function agendaIntelligenceMarkup(){
  const items=smartAgendaItems(),bills=items.filter(x=>x.type==='Bill'),tasks=items.filter(x=>x.type==='Task'),events=items.filter(x=>x.type==='Event'),special=items.filter(x=>x.type==='Birthday'||x.type==='Holiday'),total=bills.reduce((n,x)=>n+x.amount,0),next=items[0],busy=Object.values(items.reduce((out,x)=>(out[x.date]=(out[x.date]||0)+1,out),{})).reduce((max,n)=>Math.max(max,n),0);
  return `<section class="card kc44-agenda-intel" data-kc44-agenda-intel><div class="section-title"><div><div class="eyebrow">Agenda intelligence</div><h2>${items.length?'Nothing important has to sneak up on you.':'Your next seven days are open.'}</h2></div><span class="pill">${busy>=6?'Full week':busy>=3?'Balanced week':'Quiet week'}</span></div><div class="kc44-money-metrics"><div><small>Events</small><b>${events.length}</b></div><div><small>Tasks</small><b>${tasks.length}</b></div><div><small>Bills due</small><b>${bills.length}</b></div><div><small>Bill total</small><b>${money(total)}</b></div><div><small>Special dates</small><b>${special.length}</b></div><div><small>Next up</small><b>${next?new Date(`${next.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'Clear'}</b></div></div>${next?`<div class="status"><b>Prepare next:</b> ${esc(next.label)} · ${esc(next.type)}${next.location?` · ${esc(next.location)}`:''}${next.leaveTime?` · leave by ${esc(next.leaveTime)}`:''}</div>`:'<div class="status">No scheduled items require preparation during the next seven days.</div>'}<div class="calendar-connect"><span class="pill">Google Calendar: setup required</span><button class="btn ghost" type="button" data-kc44-action="google-calendar-setup">Configure Google Calendar</button><span class="pill">Apple Calendar: event export ready</span></div></section>`;
}
function readAgendaExtras(prefix){const host=$(`[data-kc44-agenda-fields="${prefix}"]`);if(!host)return null;const data={};all('[data-kc44-agenda]',host).forEach(input=>data[input.dataset.kc44Agenda]=input.value.trim());return {date:host.dataset.date,...data}}
function saveAgendaExtras(prefix){const data=readAgendaExtras(prefix);if(!data?.date)return;store.mutate(s=>{s.calendar=s.calendar||{};s.calendar[data.date]={...(s.calendar[data.date]||{}),...data};delete s.calendar[data.date].date});const status=$(`[data-kc44-agenda-fields="${prefix}"] [data-kc44-agenda-status]`);if(status)status.textContent='Directions and preparation details saved.'}
function destinationFor(prefix){const data=readAgendaExtras(prefix),location=data?.location||'';return data?.mapLink||location}
function downloadAppleDay(prefix){const data=readAgendaExtras(prefix);if(!data?.date)return;const day=store.get().calendar?.[data.date]||{},title=day.subject||String(day.events||'Appointment').split('\n')[0]||'Appointment',clean=value=>String(value||'').replace(/([,;])/g,'\\$1').replace(/\n/g,'\\n'),stamp=data.date.replaceAll('-','');const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//The Key Collective OS//Agenda//EN\r\nBEGIN:VEVENT\r\nUID:${Date.now()}@thekeycollective.os\r\nDTSTART;VALUE=DATE:${stamp}\r\nDTEND;VALUE=DATE:${stamp}\r\nSUMMARY:${clean(title)}\r\nLOCATION:${clean(data.location)}\r\nDESCRIPTION:${clean([day.notes,data.parking,data.contact&&`Contact: ${data.contact}`,data.confirmation&&`Confirmation: ${data.confirmation}`,data.appointmentNotes].filter(Boolean).join('\n'))}\r\nEND:VEVENT\r\nEND:VCALENDAR`;const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar'})),a=document.createElement('a');a.href=url;a.download=`key-collective-${data.date}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function augmentAgendaDialog(){const body=$('#agendaDialogBody6B13');if(!body)return;const date=$('#modalDate6B13')?.value;if(!date)return;body.querySelector('[data-kc44-agenda-fields="modal"]')?.remove();body.insertAdjacentHTML('beforeend',agendaConciergeFields(date,'modal'))}
function renderAgenda(){
  if((($('#page h1')?.textContent||'').trim())!=='Agenda')return;
  $('#page [data-kc44-agenda-intel]')?.remove();$('#page .pagehead')?.insertAdjacentHTML('afterend',agendaIntelligenceMarkup());
  let host=$('#page [data-kc44-agenda-fields="page"]');const date=$('#pageDate6B13')?.value||today();if(host)host.remove();const editor=$('.agenda-editor-card-6b13');if(editor)editor.insertAdjacentHTML('beforeend',agendaConciergeFields(date,'page'));
  const dateInput=$('#pageDate6B13');if(dateInput)dateInput.onchange=()=>renderAgenda();
}

function renderWellnessLinks(){
  if((($('#page h1')?.textContent||'').trim())!=='Wellness Studio')return;
  all('#page a').filter(a=>/EOS|EōS/i.test(a.textContent||'')).forEach(a=>{a.removeAttribute('target');a.href='#';a.dataset.kc44Action='open-eos';a.textContent='Open EōS Fitness App'});
}

function intelligenceMarkup(){
  const s=store.get(),stories=pulseStories(s),payments=stories.filter(x=>/payment|fintech|fraud|bank|money/i.test(`${x.topic} ${x.title}`)).slice(0,5),markets=stories.filter(x=>/market|econom|inflation|rate|employment|consumer/i.test(`${x.topic} ${x.title}`)).slice(0,4),decisions=s.intelligenceDecisions||[],watch=s.intelligenceWatchlist||['PayFac','Payments regulation','Artificial intelligence'];
  const summary=stories.slice(0,3),saved=s.savedArticles||[];
  return `<section class="kc44-intel" data-kc44-intel>
    <div class="kc44-section-head"><div><div class="eyebrow">Executive briefing suite</div><h2>From information to decisions</h2><p>Current signals, your watchlist, saved research, and the decisions they inform.</p></div><span class="pill">Private workspace</span></div>
    <div class="kc44-intel-grid">
      <article class="card kc44-span-2"><div class="section-title"><div><div class="mini">Daily Executive Briefing</div><h3>${summary.length?'Today’s priority signals':'Your briefing is ready to connect'}</h3></div><span class="pill">${s.pulseCache?.updatedAt?`Updated ${dateLabel(s.pulseCache.updatedAt)}`:'Integration-ready'}</span></div>${summary.length?summary.map(x=>`<div class="kc44-signal"><span>${esc(x.topic)}</span><div><b>${esc(x.title)}</b><p>${esc(x.why||'Review this development against your current priorities.')}</p><small>${esc(x.source||'Source pending')} · ${dateLabel(x.publishedAt)}</small></div></div>`).join(''):'<div class="status">Refresh Executive Intelligence to assemble today’s sourced briefing.</div>'}</article>
      <article class="card"><div class="mini">Why it matters to me</div><h3>Translate signal into action</h3><textarea data-kc44-field="intelligenceImpact" rows="5" placeholder="What does today’s intelligence change for your career, finances, or The Key Collective?">${esc(s.intelligenceImpact||'')}</textarea><button class="btn" data-kc44-action="save-impact">Save perspective</button></article>
      <article class="card"><div class="mini">Economic Snapshot</div><h3>Markets without the noise</h3>${markets.length?markets.map(x=>`<div class="brief-line"><span>↗</span><div><b>${esc(x.title)}</b><small>${esc(x.source||'Source')}</small></div></div>`).join(''):'<div class="status">Economic indicators will appear from your configured live feed.</div>'}</article>
      <article class="card kc44-span-2"><div class="section-title"><div><div class="mini">Payments Watch</div><h3>Payments, fraud, regulation, and operations</h3></div><span class="pill">Career-connected</span></div>${payments.length?payments.map(x=>`<div class="kc44-signal"><span>${esc(x.topic)}</span><div><b>${esc(x.title)}</b><small>${esc(x.source||'Source')} · ${dateLabel(x.publishedAt)}</small></div></div>`).join(''):'<div class="status">Payments-specific developments will appear after the next successful briefing refresh.</div>'}</article>
      <article class="card"><div class="mini">Watchlist</div><h3>What deserves your attention?</h3><div class="kc44-chips">${watch.map(x=>`<span>${esc(x)}</span>`).join('')}</div><input data-kc44-field="watch" placeholder="Add a company, regulation, or topic"><button class="btn" data-kc44-action="add-watch">Add to watchlist</button></article>
      <article class="card"><div class="mini">Saved Intelligence</div><h3>${saved.length} saved item${saved.length===1?'':'s'}</h3>${saved.slice(0,5).map(x=>`<div class="brief-line"><span>◇</span><div><b>${esc(x.title||'Saved intelligence')}</b><small>${esc(x.source||x.topic||'Research')}</small></div></div>`).join('')||'<div class="status">Save stories from your briefing to build a research library.</div>'}</article>
      <article class="card kc44-span-2"><div class="section-title"><div><div class="mini">Decision Journal</div><h3>Record the reasoning, then review the result</h3></div><span class="pill">${decisions.length} decisions</span></div><div class="kc44-form-grid"><input data-kc44-field="decision" placeholder="Decision"><textarea data-kc44-field="reason" rows="3" placeholder="Reasoning"></textarea><textarea data-kc44-field="expected" rows="3" placeholder="Expected result"></textarea><textarea data-kc44-field="outcome" rows="3" placeholder="Actual outcome (optional for now)"></textarea></div><button class="btn" data-kc44-action="save-decision">Save decision</button><div class="kc44-timeline">${decisions.slice(0,6).map((x,i)=>`<div class="entry"><div class="mini">${esc(x.date)} · Decision ${decisions.length-i}</div><b>${esc(x.decision)}</b><p>${esc(x.reason)}</p><small>Expected: ${esc(x.expected||'Not recorded')}${x.outcome?` · Outcome: ${esc(x.outcome)}`:''}</small></div>`).join('')}</div></article>
      <article class="card"><div class="mini">Weekly Intelligence Digest</div><h3>${stories.length} signals reviewed</h3><p>${payments.length} payments-related developments · ${saved.length} saved items · ${decisions.length} recorded decisions.</p><p class="muted">Your digest summarizes what you intentionally saved and reviewed—never private journal content.</p></article>
      <article class="card"><div class="mini">Source Standard</div><h3>Transparent by design</h3><p>Every live story keeps its publisher and update time. Failed feeds fall back to the last successful briefing instead of inventing headlines.</p><span class="pill">Last refresh: ${s.pulseCache?.updatedAt?dateLabel(s.pulseCache.updatedAt):'Not connected'}</span></article>
    </div></section>`;
}

function randomPrompt(category){const list=promptGroups[category]||promptGroups.Gratitude,previous=currentPrompt;currentPrompt=list.length>1?list.filter(x=>x!==previous)[Math.floor(Math.random()*(list.length-1))]:list[0];return currentPrompt}
function streak(entries){const days=new Set((entries||[]).map(x=>x.date)),d=new Date(`${today()}T12:00:00`);let n=0;while(days.has(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)){n++;d.setDate(d.getDate()-1)}return n}
function garden(entries){const count=Math.min(24,entries.length);return `<div class="kc44-garden" aria-label="Reflection garden with ${count} blooms">${Array.from({length:Math.max(6,count)},(_,i)=>`<span class="${i<count?'bloom':'seed'}">${i<count?['❀','✿','❁','⚘'][i%4]:'·'}</span>`).join('')}</div>`}
const evolutionMonths=['January','February','March','April','May','June','July','August','September','October','November','December'];
let evolutionObjectUrls=[];
function evolutionGalleryMarkup(){
  const year=new Date().getFullYear(),month=new Date().getMonth();
  return `<article class="card kc44-evolution-card"><div class="section-title"><div><div class="mini">Year in Becoming</div><h3>${year} · Watch yourself evolve</h3></div><span class="pill">Photo or 30-sec video</span></div><p class="kc44-evolution-prompt"><b>${evolutionMonths[month]} prompt:</b> Capture one honest moment that shows who you are becoming right now.</p><div class="kc44-evolution-grid" data-kc44-evolution-grid>${evolutionMonths.map((name,index)=>`<div class="kc44-evolution-month ${index===month?'current':''}" data-evolution-slot="${year}-${String(index+1).padStart(2,'0')}"><div class="kc44-evolution-preview"><span>${String(index+1).padStart(2,'0')}</span></div><strong>${name}</strong><small>${index===month?'Your moment this month':'Waiting for your moment'}</small><label class="btn ghost">Add<input type="file" accept="image/*,video/*" capture="environment" data-evolution-upload="${year}-${String(index+1).padStart(2,'0')}" hidden></label><button class="text-button" type="button" data-evolution-remove="${year}-${String(index+1).padStart(2,'0')}" hidden>Remove</button></div>`).join('')}</div><div class="status" data-evolution-status>Your monthly moments stay privately on this device.</div></article>`;
}
function videoDuration(file){return new Promise((resolve,reject)=>{const video=document.createElement('video'),url=URL.createObjectURL(file);video.preload='metadata';video.onloadedmetadata=()=>{URL.revokeObjectURL(url);resolve(video.duration)};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('That video could not be read.'))};video.src=url})}
async function hydrateEvolutionGallery(){
  const grid=$('[data-kc44-evolution-grid]');if(!grid)return;
  evolutionObjectUrls.forEach(url=>URL.revokeObjectURL(url));evolutionObjectUrls=[];
  const year=String(new Date().getFullYear()),records=(await getEvolutionMedia()).filter(record=>record.year===year);
  records.forEach(record=>{const slot=grid.querySelector(`[data-evolution-slot="${record.id}"]`);if(!slot)return;const preview=slot.querySelector('.kc44-evolution-preview'),url=URL.createObjectURL(record.blob);evolutionObjectUrls.push(url);preview.innerHTML=record.type.startsWith('video/')?`<video src="${url}" muted playsinline controls aria-label="${record.monthName} evolution video"></video>`:`<img src="${url}" alt="${record.monthName} evolution photo">`;slot.classList.add('filled');slot.querySelector('small').textContent=record.type.startsWith('video/')?'30-second video saved':'Photo saved';slot.querySelector('[data-evolution-remove]').hidden=false});
}
async function saveEvolutionUpload(input){
  const file=input.files?.[0],status=$('[data-evolution-status]');if(!file)return;
  if(!/^image\/|^video\//.test(file.type)){status.textContent='Choose a photo or video.';return}
  if(file.size>60*1024*1024){status.textContent='Choose a file smaller than 60 MB.';return}
  if(file.type.startsWith('video/')){const duration=await videoDuration(file);if(duration>30.5){status.textContent='Please choose a video that is 30 seconds or shorter.';input.value='';return}}
  const [year,month]=input.dataset.evolutionUpload.split('-');await putEvolutionMedia({id:input.dataset.evolutionUpload,year,month,monthName:evolutionMonths[Number(month)-1],type:file.type,blob:file,createdAt:new Date().toISOString()});status.textContent=`${evolutionMonths[Number(month)-1]} added to your year in becoming.`;input.value='';await hydrateEvolutionGallery();
}
function reflectionMarkup(){
  const s=store.get(),entries=s.journalEntries||[],fav=entries.filter(x=>x.favorite),key=monthKey(),monthly=s.monthlyReflections?.[key]||{},onThisDay=entries.filter(x=>String(x.date||'').slice(5)===today().slice(5)&&x.date!==today()),category=s.reflectionSettings?.category||'Gratitude';randomPrompt(category);
  return `<div class="kc44-reflection" data-kc44-reflection><div class="pagehead"><div><div class="eyebrow">Private guided reflection</div><h1>Reflection Garden</h1><p class="sub">A living archive where experiences become growth.</p></div><div class="row wrap"><span class="pill">${entries.length} reflections</span><span class="pill">${streak(entries)}-day streak</span></div></div>
  <section class="card kc44-garden-hero"><div><div class="eyebrow">Growing Garden</div><h2>${entries.length?`${entries.length} moments have taken root.`:'Plant the first thought.'}</h2><p>Every saved reflection adds another bloom. Consistency matters; length does not.</p></div>${garden(entries)}</section>
  <div class="kc44-reflection-grid"><article class="card kc44-compose"><div class="section-title"><div><div class="mini">Today’s Bloom</div><h3 data-kc44-prompt>${esc(currentPrompt)}</h3></div><button class="btn ghost" data-kc44-action="shuffle-prompt">Shuffle</button></div><div class="kc44-prompt-tabs">${Object.keys(promptGroups).map(x=>`<button class="${x===category?'active':''}" data-kc44-category="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="kc44-form-grid"><label>Mood<select data-kc44-field="mood"><option>Reflective</option><option>Grateful</option><option>Hopeful</option><option>Tender</option><option>Determined</option></select></label><label>Energy<select data-kc44-field="energy"><option>Low</option><option selected>Steady</option><option>High</option></select></label></div><textarea data-kc44-field="reflection" rows="9" placeholder="Write without editing yourself…"></textarea><div class="row wrap"><button class="btn secondary" data-kc44-action="dictate">🎙 Speak</button><label class="btn ghost kc44-attach">Attach photo or audio<input type="file" data-kc44-attachment accept="image/*,audio/*" hidden></label><button class="btn" data-kc44-action="save-reflection">Save today’s bloom</button></div><div class="status" data-kc44-attachment-status>No attachment selected.</div></article>
  <article class="card"><div class="section-title"><div><div class="mini">Memory Timeline</div><h3>Find the thread</h3></div><span class="pill">${fav.length} favorites</span></div><input data-kc44-field="journal-search" type="search" placeholder="Search entries, prompts, moods, or dates"><div class="kc44-journal-list" data-kc44-journal-list>${journalEntriesMarkup(entries)}</div></article>
  <article class="card"><div class="mini">On This Day</div><h3>A gentle look back</h3>${onThisDay.length?onThisDay.slice(0,3).map(x=>`<div class="entry"><b>${esc(x.prompt||x.category)}</b><p>${esc(x.text)}</p><small>${esc(x.date)}</small></div>`).join(''):'<div class="status">Past reflections from this date will appear here.</div>'}</article>
  <article class="card"><div class="mini">Monthly Reflection</div><h3>${new Date(`${key}-01T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h3><textarea data-kc44-month="memory" rows="2" placeholder="Favorite memory">${esc(monthly.memory||'')}</textarea><textarea data-kc44-month="lesson" rows="2" placeholder="Biggest lesson">${esc(monthly.lesson||'')}</textarea><textarea data-kc44-month="proud" rows="2" placeholder="Proudest moment">${esc(monthly.proud||'')}</textarea><textarea data-kc44-month="forward" rows="2" placeholder="What should move forward?">${esc(monthly.forward||'')}</textarea><button class="btn" data-kc44-action="save-monthly">Save monthly reflection</button></article>
  ${evolutionGalleryMarkup()}</div><div id="journalArchiveFilters" hidden></div><div id="journalTimeline" hidden></div></div>`;
}
function journalEntriesMarkup(entries){return entries.length?entries.slice(0,40).map((x,i)=>`<article class="entry"><div class="section-title"><div class="mini">${esc(x.date)} · ${esc(x.mood||x.category||'Reflection')} · ${esc(x.energy||'')}</div><button class="text-button" data-kc44-favorite="${esc(x.id||String(i))}">${x.favorite?'★':'☆'} Favorite</button></div><b>${esc(x.prompt||'Reflection')}</b><p>${esc(x.text)}</p>${x.attachment?.url?`${x.attachment.type.startsWith('image/')?`<img class="kc44-entry-image" src="${x.attachment.url}" alt="Journal attachment">`:`<audio controls src="${x.attachment.url}"></audio>`}`:''}</article>`).join(''):'<div class="status">Your first saved bloom will appear here.</div>'}

function flatten(value,path=[],out=[]){if(value==null)return out;if(typeof value==='string'||typeof value==='number'||typeof value==='boolean'){const text=String(value).trim();if(text&&!/^data:/.test(text))out.push({path,text});return out}if(Array.isArray(value))value.forEach((v,i)=>flatten(v,[...path,String(i)],out));else if(typeof value==='object')Object.entries(value).filter(([k])=>!['id','url','blob'].includes(k)).forEach(([k,v])=>flatten(v,[...path,k],out));return out}
function staticPageIndex(){const out=[];for(const [route,render] of Object.entries(pages)){try{const doc=new DOMParser().parseFromString(render(),'text/html'),text=(doc.body.textContent||'').replace(/\s+/g,' ').trim();out.push({route,type:'Page',title:routeLabels[route]||route,text})}catch{}}for(const [route,title,markup] of [['journal','Reflection Garden',reflectionMarkup()],['money','Financial Studio',forecastMarkup()]]){const doc=new DOMParser().parseFromString(markup,'text/html');out.push({route,type:'Premium feature',title,text:(doc.body.textContent||'').replace(/\s+/g,' ').trim()})}return out}
async function searchIndex(){const s=store.get(),entries=staticPageIndex();for(const item of flatten(s)){const root=item.path[0],route=dataRoutes[root]||'dashboard';entries.push({route,type:routeLabels[route]||'Saved data',title:item.path.slice(-2).join(' › '),text:item.text})}try{(await getMemos()).forEach(m=>entries.push({route:'business',type:'Voice memo',title:m.title||'Voice memo',text:`${m.title||''} ${m.createdAt||''}`}))}catch{}return entries}
async function bindGlobalSearch(){const input=$('#globalSearch'),results=$('#globalSearchResults');if(!input||!results)return;const index=await searchIndex();input.oninput=()=>{const q=input.value.trim().toLocaleLowerCase();if(!q){results.innerHTML='<div class="status">Search every page, label, saved entry, memo, bill, goal, and agenda item.</div>';return}const tokens=q.split(/\s+/).filter(Boolean),matches=index.filter(x=>tokens.every(t=>`${x.title} ${x.text} ${x.type}`.toLocaleLowerCase().includes(t)));results.innerHTML=matches.length?matches.slice(0,40).map(x=>`<button class="search-result kc44-search-result" data-kc44-route="${x.route}"><span class="pill">${esc(x.type)}</span><div><b>${esc(x.title)}</b><p>${esc(x.text).slice(0,190)}</p><small>Open ${esc(routeLabels[x.route]||x.route)} →</small></div></button>`).join(''):'<div class="status">No content matched that search.</div>'};input.placeholder='Search every word, page, entry, bill, memo, goal, or task…';results.innerHTML='<div class="status">Search every page, label, saved entry, memo, bill, goal, and agenda item.</div>'}

function dedupeMorningAcademy(){
  if((($('#page h1')?.textContent||'').trim())!=='Morning Brief')return;
  const cards=all('#page .card').filter(card=>/^Payments Academy$/i.test((card.querySelector('h3')?.textContent||'').trim()));
  if(cards.length<2)return;
  const keep=[...cards].sort((a,b)=>(b.textContent||'').length-(a.textContent||'').length)[0];
  cards.filter(card=>card!==keep).forEach(card=>card.remove());
}

let agendaBound=false;
function bindAgendaActions(){
  if(agendaBound)return;agendaBound=true;
  document.addEventListener('click',event=>{
    if(event.target.closest('[data-agenda-date]'))setTimeout(augmentAgendaDialog,0);
    const button=event.target.closest('[data-kc44-action]');if(!button)return;
    const action=button.dataset.kc44Action,prefix=button.dataset.prefix||'page';
    if(action==='save-agenda-extras'){event.preventDefault();saveAgendaExtras(prefix)}
    if(action==='open-google-directions'){event.preventDefault();const destination=destinationFor(prefix),status=button.closest('[data-kc44-agenda-fields]')?.querySelector('[data-kc44-agenda-status]');if(!destination){if(status)status.textContent='Add a location or saved Google Maps link first, then open directions.';return}window.open(/^https?:/i.test(destination)?destination:`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}`,'_blank','noopener');if(status)status.textContent='Google Maps opened in a new tab.'}
    if(action==='open-apple-directions'){event.preventDefault();const destination=destinationFor(prefix);if(destination)window.open(`https://maps.apple.com/?daddr=${encodeURIComponent(destination)}`,'_blank','noopener')}
    if(action==='export-apple-day'){event.preventDefault();downloadAppleDay(prefix)}
    if(action==='google-calendar-setup'){event.preventDefault();window.open('https://console.cloud.google.com/apis/library/calendar-json.googleapis.com','_blank','noopener')}
  });
}

function readAttachment(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);if(file.size>1500000)return reject(new Error('Choose an attachment smaller than 1.5 MB.'));const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type,url:r.result});r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function handleAction(button){const action=button.dataset.kc44Action,s=store.get();if(action==='save-impact'){store.mutate(d=>{d.intelligenceImpact=$('[data-kc44-field="intelligenceImpact"]')?.value.trim()||''})}if(action==='add-watch'){const input=$('[data-kc44-field="watch"]'),value=input?.value.trim();if(value)store.mutate(d=>{d.intelligenceWatchlist=[...new Set([...(d.intelligenceWatchlist||[]),value])]});renderBusiness()}if(action==='save-decision'){const val=k=>$(`[data-kc44-field="${k}"]`)?.value.trim()||'';if(!val('decision'))return;store.mutate(d=>{d.intelligenceDecisions=[{id:crypto.randomUUID?.()||String(Date.now()),date:today(),decision:val('decision'),reason:val('reason'),expected:val('expected'),outcome:val('outcome')},...(d.intelligenceDecisions||[])]});renderBusiness()}if(action==='save-paycheck'){const value=k=>$(`[data-kc44-pay="${k}"]`)?.value||'';store.mutate(d=>{d.financial=d.financial||{};d.financial.nextPaycheck=Math.max(0,Number(value('amount'))||0);d.financial.nextPaycheckDate=value('payDate');d.financial.paycheckPlanner={amount:Math.max(0,Number(value('amount'))||0),payDate:value('payDate')||today(),periodEnd:value('periodEnd')||addDays(value('payDate')||today(),13),assignedSavings:Math.max(0,Number(value('assignedSavings'))||0)}});renderMoney()}if(action==='open-eos'){const fallback='https://apps.apple.com/us/app/new-e%C5%8Ds-fitness/id6759914925';let timer=setTimeout(()=>{window.location.href=fallback},900);const stop=()=>{if(document.hidden){clearTimeout(timer);document.removeEventListener('visibilitychange',stop)}};document.addEventListener('visibilitychange',stop);window.location.href='eosfitness://'}if(action==='shuffle-prompt'){currentPrompt=randomPrompt(store.get().reflectionSettings?.category||'Gratitude');$('[data-kc44-prompt]').textContent=currentPrompt}if(action==='dictate'){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Voice dictation is not supported in this browser.');const r=new R();r.interimResults=true;r.onresult=e=>{$('[data-kc44-field="reflection"]').value=[...e.results].map(x=>x[0].transcript).join(' ')};r.start()}if(action==='save-reflection'){const text=$('[data-kc44-field="reflection"]')?.value.trim();if(!text)return;const mood=$('[data-kc44-field="mood"]')?.value,energy=$('[data-kc44-field="energy"]')?.value,category=store.get().reflectionSettings?.category||'Gratitude';store.mutate(d=>{d.journalEntries.unshift({id:crypto.randomUUID?.()||String(Date.now()),date:today(),category,prompt:currentPrompt,text,mood,energy,attachment,favorite:false})});attachment=null;renderJournal()}if(action==='save-monthly'){const data={};all('[data-kc44-month]').forEach(x=>data[x.dataset.kc44Month]=x.value.trim());store.mutate(d=>{d.monthlyReflections={...(d.monthlyReflections||{}),[monthKey()]:data}})}}
function renderBusiness(){
  if((($('#page h1')?.textContent||'').trim())!=='Executive Intelligence'&&((($('#page h1')?.textContent||'').trim())!=='Pulse'))return;
  $('#page [data-kc44-intel]')?.remove();
}
function shuffleVisiblePrompt(){const category=store.get().reflectionSettings?.category||'Gratitude',visible=$('[data-kc44-prompt]')?.textContent.trim()||'',list=promptGroups[category]||promptGroups.Gratitude,choices=list.filter(prompt=>prompt!==visible);currentPrompt=choices[Math.floor(Math.random()*choices.length)]||list[0];const heading=$('[data-kc44-prompt]');if(heading)heading.textContent=currentPrompt}
function renderJournal(){
  if(($('#page h1')?.textContent||'').trim()!=='Reflection Garden')return;
  $('#page').innerHTML=reflectionMarkup();
  const shuffle=$('[data-kc44-action="shuffle-prompt"]');
  if(shuffle)shuffle.onclick=event=>{event.preventDefault();event.stopPropagation();shuffleVisiblePrompt()};
  all('[data-evolution-upload]').forEach(input=>input.onchange=()=>saveEvolutionUpload(input).catch(error=>{const status=$('[data-evolution-status]');if(status)status.textContent=error.message||'That moment could not be saved.'}));
  all('[data-evolution-remove]').forEach(button=>button.onclick=async event=>{event.preventDefault();event.stopPropagation();await deleteEvolutionMedia(button.dataset.evolutionRemove);const status=$('[data-evolution-status]');if(status)status.textContent='Monthly moment removed.';await hydrateEvolutionGallery()});
  hydrateEvolutionGallery().catch(()=>{const status=$('[data-evolution-status]');if(status)status.textContent='The private media vault is unavailable in this browser.'});
  const futureButton=$('[data-kc44-action="save-future-note"]');
  if(futureButton)futureButton.onclick=event=>{
    event.preventDefault();event.stopPropagation();
    const text=$('[data-kc44-field="future-note"]')?.value.trim()||'';
    const openDate=$('[data-kc44-field="future-date"]')?.value||addDays(today(),30);
    const status=$('[data-kc44-future-status]');
    if(!text){if(status)status.textContent='Write a note before sealing it.';return}
    store.mutate(d=>{d.reflectionFutureNote={text,openDate,savedAt:new Date().toISOString()}});
    if(status)status.textContent=`Note sealed · return on ${dateLabel(openDate)}`;
  };
}
let bound=false;function bind(){if(bound)return;bound=true;document.addEventListener('click',event=>{const route=event.target.closest('[data-kc44-route]');if(route){event.preventDefault();go(route.dataset.kc44Route);return}const filter=event.target.closest('[data-kc44-bill-filter]');if(filter){event.preventDefault();const mode=filter.dataset.kc44BillFilter,now=today(),soon=addDays(now,30);all('[data-kc44-bill-filter]').forEach(x=>x.classList.toggle('active',x===filter));all('#billList22 [data-bill-id]').forEach(row=>{const paid=Boolean(row.querySelector('[data-act="paid"]')?.checked),due=row.querySelector('[data-field="due"]')?.value||'';row.hidden=mode==='paid'?!paid:mode==='due'?paid:mode==='upcoming'?(paid||!due||due<now||due>soon):false});return}const category=event.target.closest('[data-kc44-category]');if(category){store.mutate(d=>{d.reflectionSettings={...(d.reflectionSettings||{}),category:category.dataset.kc44Category}});currentPrompt=randomPrompt(category.dataset.kc44Category);all('[data-kc44-category]').forEach(x=>x.classList.toggle('active',x===category));$('[data-kc44-prompt]').textContent=currentPrompt;return}const fav=event.target.closest('[data-kc44-favorite]');if(fav){store.mutate(d=>{const entry=d.journalEntries.find((x,i)=>String(x.id||i)===fav.dataset.kc44Favorite);if(entry)entry.favorite=!entry.favorite});renderJournal();return}const action=event.target.closest('[data-kc44-action]');if(action){event.preventDefault();handleAction(action)}});document.addEventListener('change',async event=>{if(!event.target.matches('[data-kc44-attachment]'))return;try{attachment=await readAttachment(event.target.files?.[0]);$('[data-kc44-attachment-status]').textContent=attachment?`${attachment.name} ready to save.`:'No attachment selected.'}catch(error){attachment=null;$('[data-kc44-attachment-status]').textContent=error.message}});document.addEventListener('input',event=>{if(!event.target.matches('[data-kc44-field="journal-search"]'))return;const q=event.target.value.trim().toLowerCase(),entries=(store.get().journalEntries||[]).filter(x=>!q||`${x.date} ${x.category} ${x.prompt} ${x.text} ${x.mood} ${x.energy}`.toLowerCase().includes(q));$('[data-kc44-journal-list]').innerHTML=journalEntriesMarkup(entries)})}
export async function enhanceSprint6B44(id,router){routerRef=router;bind();bindAgendaActions();ensureFamilyObservances();if(id==='business')renderBusiness();if(id==='journal')renderJournal();if(id==='intelligence'){await bindGlobalSearch();dedupeMorningAcademy();requestAnimationFrame(()=>requestAnimationFrame(dedupeMorningAcademy));setTimeout(dedupeMorningAcademy,300);setTimeout(dedupeMorningAcademy,1400)}if(id==='calendar'){renderAgenda();requestAnimationFrame(()=>requestAnimationFrame(renderAgenda));setTimeout(renderAgenda,350)}if(id==='money'){renderMoney();requestAnimationFrame(()=>requestAnimationFrame(renderMoney));setTimeout(renderMoney,300);setTimeout(renderMoney,1400)}if(id==='wellness'){renderWellnessLinks();requestAnimationFrame(()=>requestAnimationFrame(renderWellnessLinks));setTimeout(renderWellnessLinks,300);setTimeout(renderWellnessLinks,1400)}const badge=$('#kcBuildStatus b');if(badge)badge.textContent=BUILD}
