import {store} from './store.js';

const $=(selector,root=document)=>root.querySelector(selector);
const all=(selector,root=document)=>[...root.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const today=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const values=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${values.year}-${values.month}-${values.day}`};

function removeMorningBriefOverload(){
  if((($('#page h1')?.textContent||'').trim())!=='Morning Brief')return;
  const remove=new Set(['25 Hard','Weekly Review','Financial Watch']);
  all('#page article.card').forEach(card=>{const heading=(card.querySelector('h2,h3')?.textContent||'').trim(),label=(card.querySelector('.mini')?.textContent||'').trim();if(remove.has(heading)||remove.has(label)||heading==='Top 3 closest goals')card.remove()});
  const metrics=$('#page .brief-metric-grid');
  if(metrics)all('article.card',metrics).forEach(card=>{if((card.querySelector('.mini')?.textContent||'').trim()==='25 Hard')card.remove()});
  const academy=all('#page article.card').filter(card=>(card.querySelector('h2,h3')?.textContent||'').trim()==='Payments Academy');
  academy.slice(1).forEach(card=>card.remove());
}

function openPriorityEditor(rank){
  const dialog=$('#priorityDialog');if(!dialog)return;
  dialog.dataset.rank=String(rank);all('[data-priority-rank]').forEach((tab,index)=>tab.classList.toggle('active',index===rank));
  const state=store.get(),detail=state.priorityDetails?.[rank]||{},title=state.top3?.[rank]||'';
  $('#priorityEditor').innerHTML=`<div class="priority-editor-grid"><label class="wide">Priority title<input id="priorityTitle" value="${esc(title)}" placeholder="Choose what deserves your energy"></label><label>Category<select id="priorityCategory">${['Personal','Family','Career','Wellness','Financial'].map(value=>`<option ${value===(detail.category||'Personal')?'selected':''}>${value}</option>`).join('')}</select></label><label>Due date<input id="priorityDue" type="date" value="${esc(detail.due||'')}"></label><label class="wide">Why this matters<textarea id="priorityWhy" rows="2">${esc(detail.why||'')}</textarea></label><label>Estimated time<input id="priorityEstimated" value="${esc(detail.estimated||'')}" placeholder="30 minutes"></label><label>Progress<input id="priorityProgress" type="range" min="0" max="100" step="5" value="${Number(detail.progress||0)}"></label><label class="wide">Notes<textarea id="priorityNotes" rows="3">${esc(detail.notes||'')}</textarea></label></div>`;
  dialog.showModal();
}
function bindPriorityEditor(){
  const dialog=$('#priorityDialog'),manage=$('#editTop3');if(!dialog||!manage||dialog.dataset.finalBound)return;dialog.dataset.finalBound='true';
  manage.onclick=()=>openPriorityEditor(0);$('#closePriorityDialog').onclick=()=>dialog.close();
  all('[data-priority-rank]').forEach((tab,index)=>tab.onclick=()=>openPriorityEditor(index));
  $('#savePriority').onclick=()=>{const rank=Number(dialog.dataset.rank||0),title=$('#priorityTitle').value.trim(),progress=Number($('#priorityProgress').value||0);store.mutate(state=>{state.priorityDetails=state.priorityDetails||[];state.priorityDetails[rank]={...(state.priorityDetails[rank]||{}),id:state.priorityDetails[rank]?.id||uid(),title,category:$('#priorityCategory').value,due:$('#priorityDue').value,why:$('#priorityWhy').value.trim(),estimated:$('#priorityEstimated').value.trim(),notes:$('#priorityNotes').value.trim(),progress,source:'Manual'};state.top3[rank]=title;state.top3Done[rank]=progress===100});const card=all('#page .priority-card')[rank];if(card){card.querySelector('b').textContent=title||`Choose priority ${rank+1}`;card.querySelector('input').checked=progress===100}dialog.close()};
  $('#clearPriority').onclick=()=>{const rank=Number(dialog.dataset.rank||0);store.mutate(state=>{state.top3[rank]='';state.top3Done[rank]=false;state.priorityDetails[rank]={id:uid(),title:'',category:'Personal',due:'',why:'',estimated:'',notes:'',progress:0,source:'Manual'}});const card=all('#page .priority-card')[rank];if(card){card.querySelector('b').textContent=`Choose priority ${rank+1}`;card.querySelector('input').checked=false}dialog.close()};
}
function makeTopThreeCardsEditable(){
  if(!$('#page .executive-focus-card'))return;
  bindPriorityEditor();
  all('#page .executive-focus-card .priority-card').forEach((card,index)=>{
    if(card.classList.contains('priority-card-editable'))return;
    card.classList.add('priority-card-editable');card.setAttribute('title',`Edit priority ${index+1}`);
    card.onclick=event=>{if(event.target.matches('input'))return;event.preventDefault();openPriorityEditor(index)};
  });
}

function ensureAgendaJumpDialog(){
  let dialog=$('#agendaJumpDialog6B46');if(dialog)return dialog;
  document.body.insertAdjacentHTML('beforeend',`<dialog id="agendaJumpDialog6B46" class="priority-dialog agenda-jump-dialog"><form method="dialog" class="priority-dialog-shell"><div class="section-title"><div><div class="eyebrow">Agenda navigation</div><h2>Jump to a date</h2></div><button class="icon-button" value="cancel" aria-label="Close">×</button></div><p class="muted">Choose a month and year, then select any date in that month.</p><div class="agenda-jump-fields"><label>Month<select id="agendaJumpMonth6B46">${Array.from({length:12},(_,i)=>`<option value="${i+1}">${new Date(2026,i,1).toLocaleDateString('en-US',{month:'long'})}</option>`).join('')}</select></label><label>Year<select id="agendaJumpYear6B46">${Array.from({length:21},(_,i)=>`<option>${2020+i}</option>`).join('')}</select><label class="wide">Date<input id="agendaJumpDate6B46" type="date" min="2020-01-01" max="2040-12-31"></label></div><div class="priority-dialog-actions"><button class="btn ghost" value="cancel">Cancel</button><button class="btn" value="default">Open date</button></div></form></dialog>`);
  dialog=$('#agendaJumpDialog6B46');$('#agendaJumpMonth6B46').onchange=syncAgendaJumpDate;$('#agendaJumpYear6B46').onchange=syncAgendaJumpDate;
  $('#agendaJumpDate6B46').onchange=()=>{const date=$('#agendaJumpDate6B46').value;if(!date)return;const [year,month]=date.split('-');$('#agendaJumpYear6B46').value=year;$('#agendaJumpMonth6B46').value=String(Number(month))};
  dialog.addEventListener('close',()=>{if(dialog.returnValue!=='default')return;const date=$('#agendaJumpDate6B46').value;if(!date)return;const native=$('#agendaMonthJump6B14');if(native){native.value=date;native.dispatchEvent(new Event('change',{bubbles:true}))}requestAnimationFrame(()=>document.querySelector(`[data-agenda-date="${date}"]`)?.focus())});return dialog;
}
function syncAgendaJumpDate(){const year=$('#agendaJumpYear6B46').value,month=String($('#agendaJumpMonth6B46').value).padStart(2,'0'),current=$('#agendaJumpDate6B46').value,day=current.slice(8)||'01',max=new Date(Number(year),Number(month),0).getDate();$('#agendaJumpDate6B46').value=`${year}-${month}-${String(Math.min(Number(day),max)).padStart(2,'0')}`}
function upgradeAgendaMonthPicker(){
  if((($('#page h1')?.textContent||'').trim())!=='Agenda')return;const button=$('#agendaMonth6B13');if(!button)return;
  button.onclick=()=>{const dialog=ensureAgendaJumpDialog(),label=button.textContent.trim(),parsed=new Date(`${label} 1`),date=$('#pageDate6B13')?.value||`${parsed.getFullYear()}-${String(parsed.getMonth()+1).padStart(2,'0')}-01`;$('#agendaJumpDate6B46').value=date;$('#agendaJumpYear6B46').value=date.slice(0,4);$('#agendaJumpMonth6B46').value=String(Number(date.slice(5,7)));dialog.showModal()};
}

function entryById(id){return (store.get().journalEntries||[]).find((entry,index)=>String(entry.id||index)===String(id))}
function updateTimeline(entry){const updates=entry.updates||[];return `<div class="memory-update-timeline">${updates.map(update=>`<article><div class="memory-update-dot">${update.final?'💡':'✦'}</div><div><div class="section-title"><span class="mini">${esc(update.date)} · ${esc(update.emotions||'Update')}</span><div class="row"><button type="button" class="text-button" data-memory-edit-update="${esc(update.id)}">Edit</button><button type="button" class="text-button" data-memory-remove-update="${esc(update.id)}">Remove</button></div></div><b>${update.final?'Final Reflection':'What Happened Next'}</b><p>${esc(update.text)}</p>${update.outcome?`<small>Outcome · ${esc(update.outcome)}</small>`:''}${update.lesson?`<small>Lesson · ${esc(update.lesson)}</small>`:''}</div></article>`).join('')||'<div class="status">No updates yet. Add one when the story moves forward.</div>'}</div>`}
function ensureMemoryDialog(){let dialog=$('#memoryDetailDialog6B46');if(dialog)return dialog;document.body.insertAdjacentHTML('beforeend',`<dialog id="memoryDetailDialog6B46" class="memory-detail-dialog"><article class="memory-detail-shell"><button type="button" class="icon-button memory-detail-close" aria-label="Close">×</button><div id="memoryDetailBody6B46"></div></article></dialog>`);dialog=$('#memoryDetailDialog6B46');$('.memory-detail-close',dialog).onclick=()=>dialog.close();dialog.onclick=event=>{if(event.target===dialog)dialog.close()};return dialog}
function memoryEditorMarkup(entry){return `<div class="eyebrow">Living Memory</div><h2>${esc(entry.title||entry.prompt||'Reflection')}</h2><p class="sub">Preserve the original thought, then record what happened next.</p><section class="memory-original"><div class="section-title"><h3>Original Reflection</h3><span class="pill">${esc(entry.date||today())}</span></div><label>Title<input data-memory-field="title" value="${esc(entry.title||entry.prompt||'Reflection')}"></label><div class="memory-field-grid"><label>Date<input type="date" data-memory-field="date" value="${esc(entry.date||today())}"></label><label>Mood<input data-memory-field="mood" value="${esc(entry.mood||entry.category||'')}"></label></div><label>Reflection<textarea data-memory-field="text" rows="6">${esc(entry.text||'')}</textarea></label><button type="button" class="btn secondary" data-memory-action="save-original">Save original reflection</button></section><section class="memory-follow-up"><div class="section-title"><div><div class="mini">What Happened Next</div><h3>Add a dated update</h3></div><span class="final-reflection-mark" title="Final Reflection uses a light bulb">💡</span></div><input type="hidden" data-memory-update-field="id"><div class="memory-field-grid"><label>Date<input type="date" data-memory-update-field="date" value="${today()}"></label><label>Emotions<input data-memory-update-field="emotions" placeholder="Proud, relieved, still processing…"></label><label>Status<select data-memory-update-field="status"><option>Still unfolding</option><option>Resolved</option><option>Lesson learned</option><option>Worth revisiting</option><option>Released</option></select></label><label class="check-label"><input type="checkbox" data-memory-update-field="final"> Final Reflection</label></div><label>How did this unfold?<textarea data-memory-update-field="text" rows="4" placeholder="What happened since the original reflection?"></textarea></label><label>Outcome<textarea data-memory-update-field="outcome" rows="2" placeholder="What was the result?"></textarea></label><label>Lesson<textarea data-memory-update-field="lesson" rows="2" placeholder="What do you want to remember?"></textarea></label><div class="row wrap"><button type="button" class="btn" data-memory-action="save-update">Save update</button><button type="button" class="btn ghost" data-memory-action="clear-update">Clear</button></div></section><section><div class="section-title"><h3>Memory Timeline</h3><span class="pill">${(entry.updates||[]).length} updates</span></div><div data-memory-timeline>${updateTimeline(entry)}</div></section>`}
function openMemory(id){const entry=entryById(id);if(!entry)return;const dialog=ensureMemoryDialog();dialog.dataset.entryId=id;$('#memoryDetailBody6B46').innerHTML=memoryEditorMarkup(entry);if(!dialog.open)dialog.showModal()}
function clearUpdateForm(){all('[data-memory-update-field]').forEach(field=>{if(field.type==='checkbox')field.checked=false;else if(field.dataset.memoryUpdateField==='date')field.value=today();else field.value=''})}
function saveOriginal(dialog){const id=dialog.dataset.entryId;store.mutate(state=>{const entry=(state.journalEntries||[]).find((item,index)=>String(item.id||index)===String(id));if(entry)all('[data-memory-field]',dialog).forEach(field=>entry[field.dataset.memoryField]=field.value.trim())});openMemory(id);decorateReflectionMemories()}
function saveUpdate(dialog){const id=dialog.dataset.entryId,value=name=>dialog.querySelector(`[data-memory-update-field="${name}"]`),text=value('text').value.trim();if(!text)return;const updateId=value('id').value||uid();store.mutate(state=>{const entry=(state.journalEntries||[]).find((item,index)=>String(item.id||index)===String(id));if(!entry)return;entry.updates=entry.updates||[];const update={id:updateId,date:value('date').value||today(),emotions:value('emotions').value.trim(),status:value('status').value,text,outcome:value('outcome').value.trim(),lesson:value('lesson').value.trim(),final:value('final').checked},index=entry.updates.findIndex(item=>item.id===updateId);if(index>=0)entry.updates[index]=update;else entry.updates.push(update)});openMemory(id);decorateReflectionMemories()}
function decorateReflectionMemories(){if((($('#page h1')?.textContent||'').trim())!=='Reflection Garden')return;const entries=store.get().journalEntries||[],cards=all('[data-kc44-journal-list] > article.entry');cards.forEach((card,index)=>{const entry=entries[index];if(!entry)return;const id=String(entry.id||index);card.classList.add('living-memory-card');if(!card.querySelector('[data-memory-open]'))card.insertAdjacentHTML('beforeend',`<div class="memory-card-footer"><span>${(entry.updates||[]).length?`${entry.updates.length} update${entry.updates.length===1?'':'s'}`:'Ready for an update'}</span><button type="button" class="btn ghost" data-memory-open="${esc(id)}">Open memory</button></div>`)})}
let bound=false;
window.addEventListener('kc:state',()=>setTimeout(decorateReflectionMemories,80));
const pageObserver=new MutationObserver(()=>{makeTopThreeCardsEditable();removeMorningBriefOverload();decorateReflectionMemories()});
pageObserver.observe(document.querySelector('#page'),{childList:true,subtree:true});
function bind(){if(bound)return;bound=true;document.addEventListener('click',event=>{const open=event.target.closest('[data-memory-open]');if(open){openMemory(open.dataset.memoryOpen);return}const dialog=event.target.closest('#memoryDetailDialog6B46');if(!dialog)return;const action=event.target.closest('[data-memory-action]');if(action?.dataset.memoryAction==='save-original')saveOriginal(dialog);if(action?.dataset.memoryAction==='save-update')saveUpdate(dialog);if(action?.dataset.memoryAction==='clear-update')clearUpdateForm();const edit=event.target.closest('[data-memory-edit-update]');if(edit){const update=entryById(dialog.dataset.entryId)?.updates?.find(item=>item.id===edit.dataset.memoryEditUpdate);if(update)Object.entries(update).forEach(([key,val])=>{const field=dialog.querySelector(`[data-memory-update-field="${key}"]`);if(field)field.type==='checkbox'?field.checked=Boolean(val):field.value=val??''})}const remove=event.target.closest('[data-memory-remove-update]');if(remove&&confirm('Remove this memory update?')){const entryId=dialog.dataset.entryId;store.mutate(state=>{const entry=(state.journalEntries||[]).find((item,index)=>String(item.id||index)===String(entryId));if(entry)entry.updates=(entry.updates||[]).filter(item=>item.id!==remove.dataset.memoryRemoveUpdate)});openMemory(entryId);decorateReflectionMemories()}})}

export async function enhanceSprint6B46(){bind();removeMorningBriefOverload();makeTopThreeCardsEditable();upgradeAgendaMonthPicker();decorateReflectionMemories();requestAnimationFrame(()=>{removeMorningBriefOverload();makeTopThreeCardsEditable();upgradeAgendaMonthPicker();decorateReflectionMemories()});setTimeout(()=>{removeMorningBriefOverload();makeTopThreeCardsEditable();upgradeAgendaMonthPicker();decorateReflectionMemories()},850)}
