import {store} from './store.js';
import {getPhotos,deletePhoto} from './photo-db.js';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2100)};
const fireworks=(mini=false)=>{const layer=document.createElement('div');layer.className=mini?'mini-fireworks':'lux-fireworks';layer.innerHTML=Array.from({length:mini?10:34},(_,i)=>`<i style="--i:${i};--x:${Math.random()*100}%;--d:${Math.random()*1.2}s"></i>`).join('');document.body.append(layer);setTimeout(()=>layer.remove(),mini?900:2200)};
export function patchPagesSprint6B(pages){
 const oldMoney=pages.money;pages.money=()=>oldMoney()+`<section class="card cash-command"><div class="section-title"><div><div class="eyebrow">Today’s money command</div><h2>Give every dollar a job.</h2></div><span class="pill">Sprint 6B</span></div><div class="cash-grid"><label>Available cash<input id="availableCash" type="number" min="0" step=".01" value="${Number(store.get().financial?.availableCash||0)}"></label><label>Last paycheck<input id="lastPaycheck" type="number" min="0" step=".01" value="${Number(store.get().financial?.lastPaycheck||0)}"></label><label>Next paycheck<input id="nextPaycheck" type="number" min="0" step=".01" value="${Number(store.get().financial?.nextPaycheck||0)}"></label><label>Expected date<input id="nextPaycheckDate" type="date" value="${esc(store.get().financial?.nextPaycheckDate||'')}"></label></div><button id="saveCashCommand" class="btn">Save cash position</button><div id="cashSummary" class="cash-summary"></div></section>`;
 const oldJournal=pages.journal;pages.journal=()=>oldJournal()+`<dialog id="reflectionDialog" class="reflection-dialog"><article class="card"><button id="closeReflection" class="icon-button reflection-close">×</button><div id="reflectionFull"></div></article></dialog>`;
}
export async function enhanceSprint6B(id,router){
 if(id==='dashboard'){focusFix();await dashboardConnectedFix();}if(id==='lani')await laniFix();if(id==='wellness')wellnessFix();if(id==='money')moneyFix();if(id==='journal')reflectionFix();if(id==='premium')designFix();if(id==='goals')hardFix();if(id==='intelligence')executiveInsightsFix();if(id==='calendar')calendarConnectedFix();
}
function focusFix(){all('[data-top3]').forEach(c=>{c.onchange=e=>{const y=scrollY,i=+c.dataset.top3;store.mutate(d=>{d.top3Done[i]=c.checked;if(d.priorityDetails?.[i])d.priorityDetails[i].progress=c.checked?100:0});requestAnimationFrame(()=>scrollTo(0,y));const done=store.get().top3Done.filter(Boolean).length;if(done===3)fireworks(false);else if(c.checked)fireworks(true)}});const card=$('.executive-focus-card');if(card&&store.get().top3Done.every(Boolean)){new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)fireworks(true)}),{threshold:.7}).observe(card)}}
async function laniFix(){const photos=await getPhotos(),stage=$('#laniSlideshow'),thumbs=$('#laniThumbs');if(!stage||!thumbs)return;let idx=Math.max(0,photos.length-1),timer;const urls=photos.map(p=>({...p,url:URL.createObjectURL(p.blob)}));const show=()=>{if(!urls.length)return;stage.innerHTML=`<img class="active" src="${urls[idx].url}" alt="Lani memory"><button id="laniPrev" class="lani-arrow prev" aria-label="Previous photo">←</button><button id="laniNext" class="lani-arrow next" aria-label="Next photo">→</button>`;$('#laniPrev').onclick=()=>{idx=(idx-1+urls.length)%urls.length;show();restart()};$('#laniNext').onclick=()=>{idx=(idx+1)%urls.length;show();restart()}};const restart=()=>{clearInterval(timer);if(urls.length>1)timer=setInterval(()=>{idx=(idx+1)%urls.length;show()},5000)};show();restart();all('[data-vault-photo]').forEach(b=>{b.onclick=async e=>{e.preventDefault();e.stopPropagation();if(e.target.closest('span')){await deletePhoto(b.dataset.vaultPhoto);toast('Photo removed.');await laniFix();return}idx=Math.max(0,urls.findIndex(x=>x.id===b.dataset.vaultPhoto));show();restart()}});const share=$('#shareLaniSnapshot');if(share)share.classList.add('contrast-safe')}
function wellnessFix(){const render=()=>{const s=store.get(),n=$('.metric');if($('#waterPlus'))$('#waterPlus').onclick=()=>{const y=scrollY;store.mutate(d=>d.water=Math.min(8,(d.water||0)+1));const val=store.get().water;const head=[...document.querySelectorAll('*')].find(x=>x.childNodes.length===1&&x.textContent.trim().match(/^\d+\/8$/));if(head)head.textContent=`${val}/8`;toast('Water saved.');requestAnimationFrame(()=>scrollTo(0,y));if(val===8)fireworks(true)};$('#saveWellness')?.addEventListener('click',()=>{});const btn=[...all('button')].find(b=>/save wellness check-in/i.test(b.textContent));if(btn)btn.onclick=()=>{const movement=+$('input[id*="gym"], input[placeholder*="Movement"], input[type="number"]')?.value||0;const nums=all('input[type="number"]');const sleep=+(nums[1]?.value||0);store.mutate(d=>{d.gymMinutes=movement;d.wellness=d.wellness||{};d.wellness.sleep=sleep;d.wellness.history=d.wellness.history||[];d.wellness.history.push({date:new Date().toISOString(),movement,sleep,mood:$('select')?.value||'Steady'})});toast('Wellness check-in saved.');fireworks(true)}};render()}
function moneyFix(){const draw=()=>{const s=store.get(),f=s.financial||{},bills=s.bills.reduce((a,b)=>a+(b.paid?0:Number(b.amount||0)),0),left=Number(f.availableCash||0)-bills;$('#cashSummary').innerHTML=`<div><small>Available today</small><strong>$${Number(f.availableCash||0).toFixed(2)}</strong></div><div><small>Unpaid bills</small><strong>$${bills.toFixed(2)}</strong></div><div><small>Safe to assign</small><strong>$${left.toFixed(2)}</strong></div>`};$('#saveCashCommand').onclick=()=>{store.mutate(d=>{d.financial={...(d.financial||{}),availableCash:+$('#availableCash').value||0,lastPaycheck:+$('#lastPaycheck').value||0,nextPaycheck:+$('#nextPaycheck').value||0,nextPaycheckDate:$('#nextPaycheckDate').value}});draw();toast('Cash position saved.');fireworks(true)};const update=[...all('button')].find(b=>/update forecast/i.test(b.textContent));if(update)update.onclick=()=>{const income=+all('input[type="number"]')[0]?.value||0,spend=+all('input[type="number"]')[1]?.value||0;store.mutate(d=>{d.monthlyIncome=income;d.financial={...(d.financial||{}),monthlySpending:spend}});toast('Forecast updated in place.');requestAnimationFrame(draw)};draw()}
function reflectionFix(){const dialog=$('#reflectionDialog'),full=$('#reflectionFull');all('#s5JournalArchive .entry').forEach((e,i)=>{e.tabIndex=0;e.setAttribute('role','button');e.onclick=()=>{const r=store.get().journalEntries[i];if(!r)return;full.innerHTML=`<div class="eyebrow">${esc(r.date)} · ${esc(r.category)}</div><h2>${esc(r.prompt||'Reflection')}</h2><p class="reflection-body">${esc(r.text)}</p><div class="row"><button class="btn ghost" id="deleteReflection">Delete</button></div>`;dialog.showModal();$('#deleteReflection').onclick=()=>{store.mutate(d=>d.journalEntries=d.journalEntries.filter(x=>x.id!==r.id));dialog.close();toast('Reflection deleted.')}};e.onkeydown=x=>{if(x.key==='Enter')e.click()}});$('#closeReflection')?.addEventListener('click',()=>dialog.close())}
function designFix(){all('[data-s5-theme]').forEach(b=>b.onclick=()=>{store.set({theme:b.dataset.s5Theme});all('[data-s5-theme]').forEach(x=>x.classList.toggle('selected',x===b));toast(`${b.querySelector('strong')?.textContent||'Theme'} applied.`);fireworks(true)});all('[data-design-pack]').forEach(b=>b.onclick=()=>{store.mutate(d=>{d.design={...(d.design||{}),pack:b.dataset.designPack,type:b.dataset.designPack}});all('[data-design-pack]').forEach(x=>x.classList.toggle('selected',x===b));toast('Typography pack applied.')} );const buttons=all('.preview-room .btn');buttons.forEach((b,i)=>b.onclick=()=>{b.classList.add('is-pressed','is-loading');setTimeout(()=>{b.classList.remove('is-loading');b.classList.add('is-success');b.textContent=i?'Secondary complete ✓':'Primary complete ✓';fireworks(true)},650);setTimeout(()=>{b.classList.remove('is-pressed','is-success');b.textContent=i?'Secondary action':'Primary action'},1700)});const tex=$('#s5Texture');if(tex)tex.onchange=()=>{store.mutate(d=>d.design={...(d.design||{}),texture:tex.value});toast(tex.value==='linen'?'Coastal Linen applied.':'Texture applied.')}}
function hardFix(){const board=$('#hardBoard');if(!board)return;all('[data-hard-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.hardView;store.set({hardView:v});board.className=`hard-board ${v==='list'?'list-view':'grid-view'}`;all('[data-hard-view]').forEach(x=>x.classList.toggle('active',x===b));toast(`${v==='list'?'List':'Grid'} view applied.`)});all('[data-hard-complete]').forEach(b=>b.addEventListener('click',()=>fireworks(true)))}


async function dashboardConnectedFix(){
 const box=$('#dashboardLani'),caption=$('#dashboardLaniCaption');if(!box)return;
 try{const photos=await getPhotos();if(photos.length){const latest=photos.at(-1),url=URL.createObjectURL(latest.blob);box.innerHTML=`<img src="${url}" alt="Lani memory" class="dashboard-lani-photo">`;if(caption)caption.textContent=store.get().laniFeaturedCaption||'A sweet moment from Lani’s Corner.';return}}
 catch(e){console.warn('Photo vault unavailable',e)}
 const legacy=store.get().laniPhotos||[];if(legacy.length){box.innerHTML=`<img src="${legacy.at(-1)}" alt="Lani memory" class="dashboard-lani-photo">`;if(caption)caption.textContent=store.get().laniFeaturedCaption||'A sweet moment from Lani’s Corner.'}
}
function buildPersonalInsights(){
 const x=store.get(),items=[];const done=(x.top3Done||[]).filter(Boolean).length;
 if(done)items.push({icon:'🎯',title:'Executive momentum',text:`${done} of your 3 priorities ${done===1?'is':'are'} complete.`});
 if((x.wellness?.history||[]).length){const h=x.wellness.history.slice(-7),avg=Math.round(h.reduce((a,v)=>a+Number(v.sleep||0),0)/h.length*10)/10;items.push({icon:'🌙',title:'Wellness pattern',text:`Your recent sleep average is ${avg} hours across ${h.length} saved check-in${h.length===1?'':'s'}.`})}
 if((x.journalEntries||[]).length){const cats={};x.journalEntries.slice(0,12).forEach(v=>cats[v.category]=(cats[v.category]||0)+1);const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];items.push({icon:'❧',title:'Reflection theme',text:`${top[0]} is your most frequent recent reflection theme.`})}
 if((x.laniMemories||[]).length)items.push({icon:'♡',title:'Family memory',text:`Lani’s Corner holds ${x.laniMemories.length} saved memor${x.laniMemories.length===1?'y':'ies'}.`});
 if((x.academy?.xp||0)>0||x.careerNotes?.length)items.push({icon:'◇',title:'Learning progress',text:`Payments Academy has ${Number(x.academy?.xp||0)} XP and ${x.careerNotes.length} saved case note${x.careerNotes.length===1?'':'s'}.`});
 const savings=(x.savingsGoals||[]).reduce((a,g)=>a+Number(g.current||0),0),target=(x.savingsGoals||[]).reduce((a,g)=>a+Number(g.target||0),0);if(target)items.push({icon:'$' ,title:'Financial progress',text:`You have funded ${Math.round(savings/target*100)}% of your active savings targets.`});
 if(!items.length)items.push({icon:'✦',title:'Your OS is listening',text:'Complete a check-in, reflection, goal, or memory to create your first personal insight.'});return items.slice(0,5)
}
function executiveInsightsFix(){
 const headers=all('h3');const h=headers.find(x=>x.textContent.trim()==='Memory Highlights');if(h){h.textContent='Executive Insights';const card=h.closest('.card');if(card){const items=buildPersonalInsights();card.querySelectorAll('.brief-line,.status').forEach(x=>x.remove());card.insertAdjacentHTML('beforeend',items.map(v=>`<div class="insight"><span>${v.icon}</span><div><b>${esc(v.title)}</b><p>${esc(v.text)}</p></div></div>`).join(''));const btn=card.querySelector('button');if(btn)btn.textContent='Open Intelligence'}}
}
function parseLines(v){return String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function dayItems(date){const x=store.get(),v=x.calendar?.[date]||{},out=[];parseLines(v.events).forEach(t=>out.push(['event','Event',t]));parseLines(v.tasks).forEach(t=>out.push(['task','Task',t]));parseLines(v.birthdays).forEach(t=>out.push(['birthday','Birthday',t]));parseLines(v.holidays).forEach(t=>out.push(['holiday','Holiday',t]));(x.bills||[]).filter(b=>b.due===date).forEach(b=>out.push(['bill','Bill',`${b.name} · $${Number(b.amount||0).toFixed(2)}`]));if(v.notes)out.push(['note','Notes',v.notes]);return out}
function icsEscape(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function exportICS(){const x=store.get(),rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//The Key Collective OS//Agenda//EN','CALSCALE:GREGORIAN'];Object.entries(x.calendar||{}).forEach(([date,v])=>{const summary=v.subject||parseLines(v.events)[0]||parseLines(v.tasks)[0]||'Key Collective Day';rows.push('BEGIN:VEVENT',`UID:${date}-${Math.random().toString(36).slice(2)}@keycollective`, `DTSTART;VALUE=DATE:${date.replaceAll('-','')}`,`DTEND;VALUE=DATE:${date.replaceAll('-','')}`,`SUMMARY:${icsEscape(summary)}`,`DESCRIPTION:${icsEscape([v.events,v.tasks,v.birthdays,v.holidays,v.notes].filter(Boolean).join('\n'))}`,'END:VEVENT')});rows.push('END:VCALENDAR');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\r\n')],{type:'text/calendar'}));a.download='key-collective-agenda.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Calendar export created.')}
function calendarConnectedFix(){
 if(!$('#agendaQuickView'))document.body.insertAdjacentHTML('beforeend',`<dialog id="agendaQuickView" class="agenda-dialog"><article class="card agenda-modal"><button id="closeAgendaQuickView" class="icon-button reflection-close">×</button><div id="agendaQuickContent"></div></article></dialog>`);
 const dialog=$('#agendaQuickView'),content=$('#agendaQuickContent');all('[data-day]').forEach(b=>{const previous=b.onclick;b.onclick=()=>{previous?.();const date=b.dataset.day,items=dayItems(date);content.innerHTML=`<div class="eyebrow">Day quick view</div><h2>${new Date(date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</h2><p class="muted">${items.length} item${items.length===1?'':'s'} connected to this day.</p><div class="agenda-quick-list">${items.length?items.map(([type,label,text])=>`<button class="agenda-quick-item ${type}" data-edit-day="${date}"><span class="agenda-dot ${type}"></span><div><small>${label}</small><b>${esc(text)}</b></div></button>`).join(''):'<div class="status">Nothing is scheduled yet. Add an event, task, birthday, holiday, note, or bill below.</div>'}</div>`;dialog.showModal();all('[data-edit-day]').forEach(x=>x.onclick=()=>{dialog.close();$('#calDate').scrollIntoView({behavior:'smooth',block:'center'});$('#calSubject').focus()})}});
 $('#closeAgendaQuickView').onclick=()=>dialog.close();$('#icsExport').onclick=exportICS;
 const p=$('#icsExport')?.closest('article')?.querySelector('p.muted');if(p)p.innerHTML='Import and export use the universal .ics format. For Google Calendar, import the file in Google Calendar settings. For Apple Calendar, open the exported file on your Apple device. Live two-way sync requires secure OAuth/calendar credentials and cannot run safely from a public GitHub Pages-only app.';
 if($('#icsExport')&&!$('#calendarConnectionPanel'))$('#icsExport').closest('.row').insertAdjacentHTML('afterend',`<div id="calendarConnectionPanel" class="calendar-connect"><a class="btn secondary" target="_blank" rel="noopener" href="https://calendar.google.com/calendar/u/0/r/settings/export">Open Google Calendar settings</a><button class="btn ghost" id="appleCalendarGuide">Apple Calendar steps</button><span class="sync-status">ICS bridge ready</span></div>`);$('#appleCalendarGuide')?.addEventListener('click',()=>toast('Export the .ics file, then open it on your iPhone, iPad, or Mac to add it to Apple Calendar.'))
}
