import {store} from './store.js';
import {loadNews,buildExecutiveSummary} from './news.js';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)};
const award=(xp,reason)=>store.mutate(d=>{d.growth=d.growth||{};d.growth.xp=Number(d.growth.xp||0)+xp;d.growth.manualWins=d.growth.manualWins||[];d.growth.manualWins.unshift({date:new Date().toISOString(),text:reason});d.growth.manualWins=d.growth.manualWins.slice(0,100)});
const celebrate=(message)=>{const el=document.createElement('div');el.className='celebration-burst';el.innerHTML='<span>✦</span><b>'+esc(message)+'</b><i>✦</i>';document.body.append(el);setTimeout(()=>el.remove(),2200)};
function pulse(){
 const render=(payload,cached=false)=>{const cats=payload.categories||{},summary=buildExecutiveSummary(cats),updated=payload.updatedAt?new Date(payload.updatedAt):null;$('#pulseHeroText').textContent=summary.length?`${summary.length} trusted U.S. developments selected for your executive briefing.`:'No trusted stories matched the strict source standard.';$('#pulseState').innerHTML=`<span class="pulse-orb"></span><b>${cached?'Cached briefing':'Trusted U.S. briefing'}</b><small>${updated?'Updated '+updated.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}):'Awaiting refresh'}</small>`;$('#pulseSummary').innerHTML=summary.slice(0,4).map(x=>`<article class="card summary-story"><span class="pill">${esc(x.topic)}</span><a href="${esc(x.url)}" target="_blank" rel="noopener"><h3>${esc(x.title)}</h3></a><p>${esc(x.why)}</p><small>${esc(x.source)} · Why it matters</small></article>`).join('');all('[data-pulse-topic]').forEach(card=>{const topic=card.dataset.pulseTopic,items=cats[topic]||[];card.querySelector('.pill').textContent=items.length?`${items.length} trusted stories`:'No match';card.querySelector('.pulse-skeleton')?.remove();card.querySelector('.pulse-list')?.remove();card.insertAdjacentHTML('beforeend',`<div class="pulse-list">${items.length?items.map(a=>`<div class="headline"><a href="${esc(a.url)}" target="_blank" rel="noopener"><b>${esc(a.title)}</b></a><small>${esc(a.source)}${a.publishedAt?' · '+new Date(a.publishedAt).toLocaleDateString('en-US',{month:'short',day:'numeric'}):''}</small><button class="save-story btn ghost" data-story='${esc(JSON.stringify({title:a.title,url:a.url,source:a.source,topic}))}'>Save</button></div>`).join(''):'<div class="pulse-empty">No trusted American source returned a matching story.</div>'}</div>`)});all('.save-story').forEach(b=>b.onclick=()=>{const a=JSON.parse(b.dataset.story);store.mutate(d=>{d.savedArticles=d.savedArticles||[];if(!d.savedArticles.some(x=>x.url===a.url))d.savedArticles.unshift({...a,savedAt:new Date().toISOString()})});b.textContent='Saved';toast('Article saved to your executive library.')})};
 const refresh=async()=>{const b=$('#refreshPulse');b.disabled=true;b.textContent='Gathering…';try{const p=await loadNews();store.set({pulseCache:p});render(p);toast('Trusted American briefing refreshed.')}catch(e){const c=store.get().pulseCache;if(c?.updatedAt){render(c,true);toast('Live sources unavailable. Showing your last briefing.')}else toast('Pulse could not reach trusted sources.')}finally{b.disabled=false;b.textContent='Refresh briefing'}};
 $('#refreshPulse').onclick=refresh;$('#pulseSettings').onclick=()=>$('#pulsePreferences').hidden=!$('#pulsePreferences').hidden;$('#closePulseSettings').onclick=()=>$('#pulsePreferences').hidden=true;all('[data-pulse-pref]').forEach(i=>i.onchange=()=>{const topics=all('[data-pulse-pref]:checked').map(x=>x.dataset.pulsePref);if(!topics.length){i.checked=true;return toast('Keep at least one channel.')}store.set({pulsePreferences:{topics}});location.reload()});const c=store.get().pulseCache;c?.updatedAt?render(c,!navigator.onLine):refresh();
}
function goals(){
 const render=()=>{const x=store.get(),items=x.goals||[],done=items.filter(g=>Number(g.progress)>=100).length;$('#hardCount').textContent=`${done}/25 complete`;$('#hardGrid').innerHTML=Array.from({length:25},(_,i)=>{const g=items[i];return `<article class="hard-card ${g&&Number(g.progress)>=100?'complete':''}"><div class="hard-number">${String(i+1).padStart(2,'0')}</div>${g?`<span class="pill">${esc(g.category||'Intentional')}</span><h3>${esc(g.name)}</h3><div class="hard-ring" style="--p:${Math.min(100,Number(g.progress||0))}%"><strong>${Number(g.progress||0)}%</strong></div><input type="range" min="0" max="100" value="${Number(g.progress||0)}" data-hard-progress="${i}"><button class="btn ghost" data-hard-remove="${i}">Remove</button>`:`<div class="hard-empty"><span>◇</span><b>Milestone waiting</b><small>Choose something worthy of becoming.</small></div>`}</article>`}).join('');all('[data-hard-progress]').forEach(r=>r.onchange=()=>{const i=+r.dataset.hardProgress,was=Number(store.get().goals[i].progress||0);store.mutate(d=>d.goals[i].progress=+r.value);if(+r.value===100&&was<100){award(250,`Completed 25 Hard milestone: ${store.get().goals[i].name}`);celebrate('Milestone unlocked · +250 XP')}render()});all('[data-hard-remove]').forEach(b=>b.onclick=()=>{store.mutate(d=>d.goals.splice(+b.dataset.hardRemove,1));render()})};
 $('#addHardGoal').onclick=()=>{const name=$('#hardGoalName').value.trim(),cat=$('#hardGoalCategory').value;if(!name)return toast('Name the milestone first.');if(store.get().goals.length>=25)return toast('Your 25 are already chosen.');store.mutate(d=>d.goals.push({name,category:cat,progress:0,createdAt:new Date().toISOString()}));award(25,`Committed to a new milestone: ${name}`);$('#hardGoalName').value='';render();toast('Milestone added · +25 XP')};render();
}
function career(){
 const quiz=[['What happens first in a card payment?',['Settlement','Authorization','Chargeback'],'Authorization'],['Which network message confirms issuer approval?',['Authorization response','Batch close','Payout file'],'Authorization response'],['What best describes settlement?',['Moving cleared funds','Creating a token','Opening a dispute'],'Moving cleared funds']];
 let i=Number(store.get().academy?.quizIndex||0)%quiz.length;const render=()=>{const [q,opts]=quiz[i];$('#quizQuestion').textContent=q;$('#quizOptions').innerHTML=opts.map(o=>`<button class="quiz-option" data-answer="${esc(o)}">${esc(o)}</button>`).join('');all('[data-answer]').forEach(b=>b.onclick=()=>{const correct=b.dataset.answer===quiz[i][2];b.classList.add(correct?'correct':'wrong');if(correct){store.mutate(d=>{d.academy=d.academy||{};d.academy.completed=Number(d.academy.completed||0)+1;d.academy.quizIndex=(i+1)%quiz.length});award(100,'Completed a Payments Academy knowledge check');celebrate('Knowledge unlocked · +100 XP');setTimeout(()=>location.reload(),900)}else toast('Not quite—follow the payment flow and try again.')})};render();
 $('#saveAcademyNote').onclick=()=>{const text=$('#academyNote').value.trim();if(!text)return;store.mutate(d=>d.careerNotes.unshift({date:new Date().toISOString(),text}));$('#academyNote').value='';toast('Case note saved.')};
}
function wellness(){all('[data-water]').forEach(b=>b.onclick=()=>{store.set({water:Math.max(0,Math.min(8,store.get().water+Number(b.dataset.water)))});location.reload()});$('#saveWellness').onclick=()=>{store.mutate(d=>{d.gymMinutes=Number($('#wellMinutes').value||0);d.wellness=d.wellness||{};d.wellness.sleep=Number($('#wellSleep').value||0);d.wellness.mood=$('#wellMood').value;d.wellness.recovery=Number($('#wellRecovery').value||0);d.wellness.history=d.wellness.history||[];d.wellness.history.unshift({date:new Date().toISOString().slice(0,10),sleep:d.wellness.sleep,mood:d.wellness.mood,recovery:d.wellness.recovery,water:d.water,minutes:d.gymMinutes});d.wellness.history=d.wellness.history.slice(0,90)});award(40,'Completed a Wellness Studio check-in');toast('Wellness check-in saved · +40 XP')};}
function money(){$('#saveForecast').onclick=()=>{store.mutate(d=>{d.monthlyIncome=Number($('#forecastIncome').value||0);d.financial=d.financial||{};d.financial.monthlySpending=Number($('#forecastSpending').value||0)});toast('Cash-flow forecast updated.');location.reload()};}
function journal(){const render=()=>{const q=$('#journalSearch').value.toLowerCase(),m=$('#journalMoodFilter').value,items=store.get().journalEntries.filter(e=>(!q||[e.text,e.prompt,e.category].join(' ').toLowerCase().includes(q))&&(!m||e.mood===m));$('#journalLibrary').innerHTML=items.length?items.map(e=>`<article class="entry journal-entry"><div class="section-title"><span class="pill">${esc(e.mood||'Reflective')}</span><small>${esc(e.date||'')}</small></div><b>${esc(e.category||'Reflection')}</b><p>${esc(e.text)}</p></article>`).join(''):'<div class="status">Your story begins with today’s first reflection.</div>'};$('#journalSearch').oninput=render;$('#journalMoodFilter').onchange=render;$('#saveSprint3Reflection').onclick=()=>{const text=$('#s3Reflection').value.trim();if(!text)return toast('Write a reflection first.');store.mutate(d=>d.journalEntries.unshift({date:new Date().toISOString().slice(0,10),category:'Reflection',prompt:'What did today reveal?',text,mood:$('#s3Mood').value}));award(35,'Saved a Reflection Garden entry');$('#s3Reflection').value='';render();toast('Reflection saved · +35 XP')};render();}
export function enhance(id,router){all('[data-jump]').forEach(b=>b.onclick=()=>router.go(b.dataset.jump));requestAnimationFrame(()=>document.querySelector('.page')?.classList.add('page-enter'));({business:pulse,goals,career,wellness,money,journal}[id]?.())}
