import {store} from './store.js';
const $=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notify(title,message,type='success'){
 let host=$('#luxNotifications');if(!host){host=document.createElement('div');host.id='luxNotifications';host.className='lux-notifications';host.setAttribute('aria-live','polite');document.body.append(host)}
 const n=document.createElement('div');n.className=`lux-notice ${type}`;n.innerHTML=`<span class="notice-mark">${type==='success'?'✓':type==='warn'?'!':'✦'}</span><div><b>${esc(title)}</b><small>${esc(message)}</small></div>`;host.append(n);requestAnimationFrame(()=>n.classList.add('show'));setTimeout(()=>{n.classList.remove('show');setTimeout(()=>n.remove(),250)},2600)
}
function dateToGoogle(date,days=1){const d=String(date||new Date().toISOString().slice(0,10)).replaceAll('-','');const end=new Date((date||new Date().toISOString().slice(0,10))+'T12:00:00');end.setDate(end.getDate()+days);return `${d}/${end.toISOString().slice(0,10).replaceAll('-','')}`}
function downloadICS(filename='key-collective-agenda.ics'){
 const x=store.get(),rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//The Key Collective OS//Sprint 6B.1//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH'];
 Object.entries(x.calendar||{}).sort(([a],[b])=>a.localeCompare(b)).forEach(([date,v])=>{const description=[v.events,v.tasks,v.birthdays,v.holidays,v.notes].filter(Boolean).join('\\n');const summary=v.subject||String(v.events||v.tasks||'Key Collective Day').split(/\n/)[0];rows.push('BEGIN:VEVENT',`UID:${date}@thekeycollective.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${date.replaceAll('-','')}`,`DTEND;VALUE=DATE:${dateToGoogle(date).split('/')[1]}`,`SUMMARY:${String(summary).replace(/[\\,;]/g,m=>'\\'+m)}`,`DESCRIPTION:${String(description).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/[,;]/g,m=>'\\'+m)}`,'END:VEVENT')});rows.push('END:VCALENDAR');
 const blob=new Blob([rows.join('\r\n')],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200);return rows.length;
}
function calendarBridge(){
 const exportBtn=$('#icsExport');if(!exportBtn)return;
 exportBtn.onclick=()=>{downloadICS();notify('Calendar export ready','A standards-compliant .ics file was created for Google or Apple Calendar.')};
 const old=$('#calendarConnectionPanel');old?.remove();
 exportBtn.closest('.row')?.insertAdjacentHTML('afterend',`<section id="calendarConnectionPanel" class="calendar-bridge"><div class="section-title"><div><div class="eyebrow">Calendar bridge</div><h3>Google + Apple Calendar</h3></div><span class="sync-status" id="calendarBridgeStatus">Ready</span></div><p class="muted">Use the universal calendar bridge below. Your agenda remains private on this device until you choose to send or import it.</p><div class="provider-grid"><article><b>Google Calendar</b><small>Add the selected day directly, or import the complete .ics export.</small><button class="btn secondary" id="googleAddDay">Add selected day</button><a class="btn ghost" target="_blank" rel="noopener" href="https://calendar.google.com/calendar/u/0/r/settings/export">Open Google import settings</a></article><article><b>Apple Calendar</b><small>Download the complete calendar and open it on iPhone, iPad, or Mac.</small><button class="btn secondary" id="appleExport">Open in Apple Calendar</button><button class="btn ghost" id="appleInstructions">Connection instructions</button></article></div><div class="bridge-checks"><span>✓ ICS 2.0 export</span><span>✓ Google event handoff</span><span>✓ Apple file handoff</span><span>✓ Local .ics import</span></div></section>`);
 $('#googleAddDay').onclick=()=>{const date=$('#calDate')?.value||new Date().toISOString().slice(0,10),v=store.get().calendar?.[date]||{},text=[v.events,v.tasks,v.birthdays,v.holidays,v.notes].filter(Boolean).join('\n'),url=new URL('https://calendar.google.com/calendar/render');url.searchParams.set('action','TEMPLATE');url.searchParams.set('text',v.subject||'Key Collective Day');url.searchParams.set('dates',dateToGoogle(date));url.searchParams.set('details',text||'Planned in The Key Collective OS');window.open(url.toString(),'_blank','noopener');store.mutate(d=>{d.calendarConnections={...(d.calendarConnections||{}),google:{mode:'handoff',lastUsed:new Date().toISOString()}}});$('#calendarBridgeStatus').textContent='Google handoff opened';notify('Google Calendar opened','Review the event and tap Save in Google Calendar.')};
 $('#appleExport').onclick=()=>{downloadICS('the-key-collective-apple-calendar.ics');store.mutate(d=>{d.calendarConnections={...(d.calendarConnections||{}),apple:{mode:'ics',lastUsed:new Date().toISOString()}}});$('#calendarBridgeStatus').textContent='Apple file created';notify('Apple Calendar file ready','Open the downloaded file to add it to Apple Calendar.')};
 $('#appleInstructions').onclick=()=>notify('Apple Calendar connection','Open the exported .ics file, choose Add All, then select your destination calendar.','info');
}
function globalContrast(){document.documentElement.classList.add('sprint-6b1');all('.ritual-editor input,.ritual-editor textarea').forEach(x=>x.classList.add('contrast-input'))}
function growthPolish(){
 const cards=all('.achievement');cards.forEach((c,i)=>{c.style.setProperty('--delay',`${i*60}ms`);c.classList.add('achievement-ready')});
 const buttons=all('#main button');buttons.forEach(b=>{if(b.dataset.luxBound)return;b.dataset.luxBound='1';b.addEventListener('pointerdown',()=>b.classList.add('lux-pressed'));b.addEventListener('pointerup',()=>setTimeout(()=>b.classList.remove('lux-pressed'),120));b.addEventListener('pointercancel',()=>b.classList.remove('lux-pressed'))})
}
function intelligenceReceipt(){
 if(!['intelligence','business'].some(x=>location.hash.includes(x)))return;const x=store.get(),count=(x.journalEntries?.length||0)+(x.wellness?.history?.length||0)+(x.wins?.length||0)+(x.calendar?Object.keys(x.calendar).length:0);const h=[...all('h1')][0];if(h&&!$('#intelligenceReceipt'))h.closest('.pagehead')?.insertAdjacentHTML('afterend',`<div id="intelligenceReceipt" class="intelligence-receipt"><span>✦</span><div><b>Intelligence grounded in your OS</b><small>${count} saved signals reviewed across reflections, wellness, wins, and agenda.</small></div></div>`)
}
export function enhanceSprint6B1(id){globalContrast();growthPolish();if(id==='calendar')calendarBridge();if(id==='intelligence'||id==='business')intelligenceReceipt();if(id==='sanctuary')notify('Sanctuary contrast applied','Dark-theme typography is now using the luxury ivory hierarchy.','info')}
