const CURRENT_KEY='keyCollectiveOS.core.v4';
const LEGACY_KEYS=['keyCollectiveOS.core.v3','keyCollectiveOS.core.v2','keyCollectiveOS.core.v1','theKeyCollectiveOS_v4','theKeyCollectiveOS_v4_1'];
const RECOVERY_KEY='keyCollectiveOS.recovery.v4';
const defaults={schemaVersion:10,theme:'champagne',design:{motion:'standard',cards:'glass',radius:'soft',texture:'clean',type:'classic'},profile:{name:'Alexis',title:'Founder of The Key Collective',mission:'Unlock the life you’re building, one intentional choice at a time.',vision:'Build a life that feels as intentional as it looks.',values:['Intention','Family','Growth','Freedom'],annualTheme:'Becoming',fiveYearVision:'',legacy:''},checking:0,savings:0,otherAssets:0,debts:0,monthlyIncome:0,bills:[],calendar:{},top3:['','',''],top3Done:[false,false,false],water:0,gymMinutes:0,goals:[],journalEntries:[],journalPromptHistory:{},laniPhotos:[],laniFacts:{birthday:'',age:'',height:'',favoriteColor:'',foods:'',toys:'',shows:'',activities:'',clothingSize:'',shoeSize:'',giftIdeas:'',medications:'',allergies:''},laniMemories:[],laniSwim:{goggles:false,towel:false,suit:false,snack:false,water:false,sunscreen:false},laniPrep:{outfit:false,bag:false,calendar:false,meal:false},laniPhotoIndex:0,newsTopics:['U.S. News','Arizona + Phoenix','Payments + Fintech','AI + Technology','Markets + Economy','Business'],careerNotes:[],savingsGoals:[],sinkingFunds:[],wins:[],dailyBriefNotes:'',weeklyReviews:[],dashboardPins:['calendar','money','lani','wellness'],pulseCache:{categories:{},updatedAt:'',source:''},pulsePreferences:{topics:['U.S. News','Arizona + Phoenix','Payments + Fintech','AI + Technology','Markets + Economy','Business']},growth:{xp:0,manualWins:[],lastCheckIn:'',streak:0},sanctuary:{completed:{},notes:{}},savedArticles:[],academy:{completed:0,quizIndex:0},wellness:{sleep:0,mood:'Steady',recovery:70,history:[]},financial:{monthlySpending:0},lastSaved:''};
function merge(v={}){const legacyTheme=v.theme==='night'?'midnight':v.theme==='light'?'champagne':v.theme;return {...defaults,...v,theme:legacyTheme||defaults.theme,design:{...defaults.design,...(v.design||{})},profile:{...defaults.profile,...(v.profile||{})},schemaVersion:10,laniFacts:{...defaults.laniFacts,...(v.laniFacts||{})},laniSwim:{...defaults.laniSwim,...(v.laniSwim||{})},laniPrep:{...defaults.laniPrep,...(v.laniPrep||{})}}}
function valid(v){return v&&typeof v==='object'&&Array.isArray(v.bills)&&Array.isArray(v.goals)&&Array.isArray(v.journalEntries)&&v.calendar&&typeof v.calendar==='object'}
function migrate(){for(const key of LEGACY_KEYS){const raw=localStorage.getItem(key);if(raw){try{const old=JSON.parse(raw);if(valid(merge(old))){const next=merge(old);localStorage.setItem(CURRENT_KEY,JSON.stringify(next));return next}}catch{}}}return merge({})}
let state=(()=>{try{const raw=localStorage.getItem(CURRENT_KEY);const parsed=raw?JSON.parse(raw):null;return valid(parsed)?merge(parsed):migrate()}catch{return migrate()}})();
function persist(next){try{localStorage.setItem(RECOVERY_KEY,JSON.stringify(state));state=merge({...next,lastSaved:new Date().toISOString()});localStorage.setItem(CURRENT_KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('kc:state',{detail:state}))}catch(err){console.error(err);throw new Error('Your browser could not save this update. Export a backup and free some storage.') }}
export const store={get:()=>state,set(patch){persist({...state,...patch})},mutate(fn){const draft=structuredClone(state);fn(draft);persist(draft)},export(){return JSON.stringify({app:'The Key Collective OS',exportedAt:new Date().toISOString(),schemaVersion:10,data:state},null,2)},import(text){const parsed=JSON.parse(text);const data=parsed?.data||parsed;if(!valid(merge(data)))throw new Error('Backup structure is invalid');persist(data)},recover(){const raw=localStorage.getItem(RECOVERY_KEY);if(!raw)return false;const data=JSON.parse(raw);if(!valid(merge(data)))return false;persist(data);return true},validate(){const issues=[];if(!valid(state))issues.push('Core data structure is incomplete');if(state.schemaVersion!==10)issues.push('Schema version is outdated');return{ok:issues.length===0,issues,schemaVersion:state.schemaVersion,lastSaved:state.lastSaved}},key:CURRENT_KEY};
